Repository python-kasa/python-kasa, pull requests merged in 2022-10, with the labels that each got.

#372 Fix year emeter for cli by using kwarg for year parameter
  kasa/cli.py
  kasa/tests/test_cli.py
Labels: bug

#377 Clarify information about supported devices
  README.md
Labels: documentation

#380 Add ToCs for doc pages
  docs/source/cli.rst
  docs/source/design.rst
  docs/source/discover.rst
  docs/source/smartbulb.rst
  docs/source/smartdevice.rst
  docs/source/smartdimmer.rst
  docs/source/smartlightstrip.rst
  docs/source/smartplug.rst
  docs/source/smartstrip.rst
Labels: documentation

#382 Fix outdated smartstrip cli examples
  docs/source/smartstrip.rst
Labels: documentation

#379 Add support for bulb presets
  docs/source/smartbulb.rst
  kasa/__init__.py
  kasa/cli.py
  kasa/smartbulb.py
  kasa/tests/newfakes.py
  kasa/tests/test_bulb.py
Labels: enhancement
