Repository python-kasa/python-kasa, pull requests merged in 2022-04, with the labels that each got.

#330 Ensure bulb state is restored when turning back on
  kasa/smartbulb.py
  kasa/tests/test_bulb.py
Labels: bug

#333 Various documentation updates
  .pre-commit-config.yaml
  docs/source/design.rst
  docs/source/index.rst
  docs/source/smartbulb.rst
  docs/source/smartdevice.rst
  docs/source/smartdimmer.rst
  docs/source/smartlightstrip.rst
  docs/source/smartplug.rst
  docs/source/smartstrip.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#334 Export modules & make sphinx happy
  docs/source/design.rst
  kasa/modules/__init__.py
  kasa/smartbulb.py
  kasa/smartdimmer.py
  kasa/smartplug.py
  kasa/smartstrip.py
Labels: documentation

#335 Avoid discovery on --help
  kasa/cli.py
Labels: bug

#336 Drop deprecated, type-specific options in favor of --type
  kasa/cli.py
  kasa/tests/test_cli.py
Labels: breaking
