Repository python-kasa/python-kasa, pull requests merged in 2023-05, with the labels that each got.

#455 Drop python 3.7 support
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  kasa/tests/test_cli.py
  kasa/tests/test_discovery.py
  kasa/tests/test_protocol.py
  kasa/tests/test_readme_examples.py
  pyproject.toml
Labels: breaking change

#453 Add inactivity setting for the motion module
  kasa/modules/motion.py
Labels: enhancement

#429 Add methods to configure dimmer settings
  kasa/smartdimmer.py
Labels: enhancement

#451 Exclude querying certain modules for KL125(US) which cause crashes
  kasa/smartdevice.py
Labels: bug
