Repository python-kasa/python-kasa, pull requests merged in 2023-11, with the labels that each got.

#539 Update discover single to handle hostnames
  kasa/discover.py
  kasa/tests/test_discovery.py
Labels: enhancement

#541 Add some more external links to README
  README.md
Labels: documentation

#509 Add klap protocol
  kasa/__init__.py
  kasa/cli.py
  kasa/discover.py
  kasa/klapprotocol.py
  kasa/protocol.py
  kasa/smartdevice.py
  kasa/tests/test_discovery.py
  kasa/tests/test_klapprotocol.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#538 Move connect_single to SmartDevice.connect
  docs/source/design.rst
  kasa/cli.py
  kasa/device_factory.py
  kasa/device_type.py
  kasa/discover.py
  kasa/smartdevice.py
  kasa/tests/test_cli.py
  kasa/tests/test_device_factory.py
  kasa/tests/test_device_type.py
  kasa/tests/test_discovery.py
  kasa/tests/test_smartdevice.py
Labels: enhancement, breaking change

#554 Set TCP_NODELAY to avoid needless buffering
  kasa/protocol.py
Labels: enhancement

#551 Re-add protocol_class parameter to connect
  kasa/device_factory.py
  kasa/tests/test_device_factory.py
Labels: enhancement

#556 Update dump_devinfo to include 20002 discovery results
  devtools/dump_devinfo.py
  kasa/discover.py
  kasa/smartdevice.py
  kasa/tests/fixtures/HS100(UK)_4.1_1.1.0.json
  kasa/tests/newfakes.py
Labels: enhancement

#552 Add support for the protocol used by TAPO devices and some newer KASA devices.
  kasa/aesprotocol.py
  kasa/device_factory.py
  kasa/device_type.py
  kasa/discover.py
  kasa/tapo/tapodevice.py
  kasa/tapo/tapoplug.py
  kasa/tests/test_discovery.py
Labels: enhancement
