Repository python-kasa/python-kasa, pull requests merged in 2023-02, with the labels that each got.

#403 Use rich for prettier output, if available
  devtools/parse_pcap.py
  kasa/cli.py
  kasa/tests/test_cli.py
Labels: enhancement

#428 Pretty-print all exceptions from cli commands
  kasa/cli.py
Labels: enhancement

#416 Add transition parameter to lightstrip's set_effect
  kasa/smartlightstrip.py
  kasa/tests/test_lightstrip.py
Labels: enhancement

#394 Return usage.get_{monthstat,daystat} in expected format
  kasa/modules/emeter.py
  kasa/modules/usage.py
  kasa/smartdevice.py
  kasa/tests/test_usage.py
Labels: bug

#431 Minor fixes to smartbulb docs
  docs/source/smartbulb.rst
  kasa/smartbulb.py
Labels: documentation

#430 Add support for json output
  kasa/cli.py
  kasa/tests/test_cli.py
Labels: enhancement
