Repository python-kasa/python-kasa, pull requests merged in 2023-12, with the labels that each got.

#561 Update dump_devinfo to produce new TAPO/SMART fixtures
  devtools/dump_devinfo.py
  kasa/tapo/__init__.py
  kasa/tapo/tapodevice.py
Labels: enhancement

#557 Add klap support for TAPO protocol by splitting out Transports and Protocols
  kasa/__init__.py
  kasa/aesprotocol.py
  kasa/aestransport.py
  kasa/device_factory.py
  kasa/discover.py
  kasa/iotprotocol.py
  kasa/klaptransport.py
  kasa/protocol.py
  kasa/smartdevice.py
  kasa/smartprotocol.py
  kasa/tapo/tapodevice.py
  kasa/tests/conftest.py
  kasa/tests/fixtures/smart/P110_1.0_1.3.0.json
  kasa/tests/newfakes.py
  kasa/tests/test_cli.py
  kasa/tests/test_device_factory.py
  kasa/tests/test_discovery.py
  kasa/tests/test_klapprotocol.py
  kasa/tests/test_plug.py
  kasa/tests/test_readme_examples.py
  kasa/tests/test_smartdevice.py
Labels: enhancement

#558 Add support for tapo bulbs
  devtools/check_readme_vs_fixtures.py
  kasa/device_factory.py
  kasa/device_type.py
  kasa/tapo/__init__.py
  kasa/tapo/tapobulb.py
  kasa/tests/conftest.py
  kasa/tests/fixtures/smart/L530E(EU)_3.0_1.0.6.json
  kasa/tests/newfakes.py
  kasa/tests/test_bulb.py
  kasa/tests/test_discovery.py
Labels: enhancement

#570 Use consistent naming for cli envvars
  kasa/cli.py
Labels: enhancement

#571 Update readme with clearer instructions, tapo support
  README.md
Labels: documentation

#567 Add KP125M fixture and allow passing credentials for tests
  kasa/tests/conftest.py
  kasa/tests/fixtures/smart/KP125M(US)_1.0_1.1.3.json
Labels: enhancement

#576 Request component_nego only once for tapodevice
  kasa/tapo/tapodevice.py
Labels: enhancement

#578 Improve smartprotocol error handling and retries
  kasa/aestransport.py
  kasa/exceptions.py
  kasa/klaptransport.py
  kasa/smartprotocol.py
  kasa/tapo/tapobulb.py
  kasa/tests/newfakes.py
  kasa/tests/test_klapprotocol.py
Labels: enhancement

#583 Improve CLI Discovery output
  kasa/cli.py
  kasa/discover.py
  kasa/exceptions.py
  kasa/tests/conftest.py
  kasa/tests/newfakes.py
  kasa/tests/test_cli.py
  kasa/tests/test_discovery.py
Labels: enhancement

#584 Enable multiple requests in smartprotocol
  kasa/aestransport.py
  kasa/iotprotocol.py
  kasa/smartprotocol.py
  kasa/tapo/tapodevice.py
  kasa/tapo/tapoplug.py
  kasa/tests/conftest.py
  kasa/tests/newfakes.py
  kasa/tests/test_aestransport.py
  kasa/tests/test_emeter.py
  kasa/tests/test_klapprotocol.py
  kasa/tests/test_smartdevice.py
  kasa/tests/test_smartprotocol.py
Labels: enhancement

#569 Add DeviceConfig to allow specifying configuration parameters
  docs/source/design.rst
  docs/source/deviceconfig.rst
  docs/source/index.rst
  kasa/__init__.py
  kasa/aestransport.py
  kasa/cli.py
  kasa/credentials.py
  kasa/device_factory.py
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/iotprotocol.py
  kasa/klaptransport.py
  kasa/protocol.py
  kasa/smartbulb.py
  kasa/smartdevice.py
  kasa/smartdimmer.py
  kasa/smartlightstrip.py
  kasa/smartplug.py
  kasa/smartprotocol.py
  kasa/smartstrip.py
  kasa/tapo/tapodevice.py
  kasa/tapo/tapoplug.py
  kasa/tests/conftest.py
  kasa/tests/newfakes.py
  kasa/tests/test_aestransport.py
  kasa/tests/test_cli.py
  kasa/tests/test_device_factory.py
  kasa/tests/test_deviceconfig.py
  kasa/tests/test_discovery.py
  kasa/tests/test_klapprotocol.py
  kasa/tests/test_protocol.py
  kasa/tests/test_smartdevice.py
  kasa/tests/test_smartprotocol.py
Labels: enhancement, breaking change
