Repository python-kasa/python-kasa, pull requests merged in 2024-05, with the labels that each got.

#870 Improve feature setter robustness
  kasa/feature.py
  kasa/iot/iotbulb.py
  kasa/smart/modules/autooffmodule.py
  kasa/smart/modules/colortemp.py
  kasa/smart/modules/lighttransitionmodule.py
  kasa/smart/modules/temperature.py
  kasa/tests/device_fixtures.py
  kasa/tests/test_feature.py
Labels: bug

#887 Add LightEffectModule for dynamic light effects on SMART bulbs
  kasa/cli.py
  kasa/feature.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/lighteffectmodule.py
  kasa/smart/smartdevice.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/smart/modules/test_light_effect.py
  kasa/tests/test_cli.py
Labels: enhancement

#894 Use Path.save for saving the fixtures
  devtools/dump_devinfo.py
Labels: bug

#892 Make get_module return typed module
  kasa/device.py
  kasa/iot/iotdevice.py
  kasa/module.py
  kasa/smart/smartdevice.py
  kasa/tests/smart/features/test_brightness.py
  kasa/tests/smart/modules/test_fan.py
  kasa/tests/test_iotdevice.py
  kasa/tests/test_smartdevice.py
Labels: enhancement

#899 Add missing alarm volume 'normal'
  kasa/feature.py
  kasa/smart/modules/alarmmodule.py
Labels: bug

#904 Improve categorization of features
  kasa/feature.py
  kasa/iot/iotbulb.py
  kasa/iot/iotdevice.py
  kasa/iot/iotdimmer.py
  kasa/iot/iotplug.py
  kasa/iot/modules/ambientlight.py
  kasa/iot/modules/cloud.py
  kasa/iot/modules/emeter.py
  kasa/module.py
  kasa/smart/modules/alarmmodule.py
  kasa/smart/modules/autooffmodule.py
  kasa/smart/modules/battery.py
  kasa/smart/modules/brightness.py
  kasa/smart/modules/cloudmodule.py
  kasa/smart/modules/colormodule.py
  kasa/smart/modules/colortemp.py
  kasa/smart/modules/energymodule.py
  kasa/smart/modules/fanmodule.py
  kasa/smart/modules/firmware.py
  kasa/smart/modules/frostprotection.py
  kasa/smart/modules/humidity.py
  kasa/smart/modules/ledmodule.py
  kasa/smart/modules/lighteffectmodule.py
  kasa/smart/modules/lighttransitionmodule.py
  kasa/smart/modules/reportmodule.py
  kasa/smart/modules/temperature.py
  kasa/smart/modules/temperaturecontrol.py
  kasa/smart/modules/timemodule.py
  kasa/smart/modules/waterleak.py
  kasa/smart/smartdevice.py
  kasa/tests/test_feature.py
Labels: enhancement

#902 Add warning about tapo watchdog
  docs/source/cli.rst
Labels: documentation

#906 Add 'battery_percentage' only when it's available
  kasa/smart/modules/battery.py
Labels: bug

#877 Add support for contact sensor (T110)
  README.md
  SUPPORTED.md
  kasa/smart/modules/__init__.py
  kasa/smart/modules/contact.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  kasa/tests/device_fixtures.py
  kasa/tests/fixtures/smart/child/T110(EU)_1.0_1.8.0.json
  kasa/tests/smart/modules/test_contact.py
Labels: enhancement

#901 Move contribution instructions into docs
  CONTRIBUTING.md
  README.md
  docs/source/contribute.md
  docs/source/index.rst
Labels: documentation

#791 Improve smartdevice update module
  kasa/smart/modules/firmware.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/smart/modules/test_firmware.py
Labels: enhancement

#895 Create common interfaces for remaining device types
  .pre-commit-config.yaml
  devtools/create_module_fixtures.py
  kasa/__init__.py
  kasa/bulb.py
  kasa/device.py
  kasa/interfaces/led.py
  kasa/interfaces/lighteffect.py
  kasa/iot/effects.py
  kasa/iot/iotdevice.py
  kasa/iot/iotlightstrip.py
  kasa/iot/iotmodule.py
  kasa/iot/iotplug.py
  kasa/iot/iotstrip.py
  kasa/iot/modules/__init__.py
  kasa/iot/modules/ledmodule.py
  kasa/iot/modules/lighteffectmodule.py
  kasa/module.py
  kasa/modulemapping.py
  kasa/modulemapping.pyi
  kasa/plug.py
  kasa/smart/modules/ledmodule.py
  kasa/smart/modules/lighteffectmodule.py
  kasa/smart/smartdevice.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/smart/features/test_brightness.py
  kasa/tests/smart/modules/test_contact.py
  kasa/tests/smart/modules/test_fan.py
  kasa/tests/smart/modules/test_firmware.py
  kasa/tests/smart/modules/test_light_effect.py
  kasa/tests/test_common_modules.py
  kasa/tests/test_iotdevice.py
  kasa/tests/test_lightstrip.py
  kasa/tests/test_smartdevice.py
Labels: enhancement

#919 Add tutorial doctest module and enable top level await
  README.md
  docs/source/conf.py
  docs/source/design.rst
  docs/source/device.rst
  docs/source/discover.rst
  docs/source/index.rst
  docs/source/smartbulb.rst
  docs/source/tutorial.md
  docs/tutorial.py
  kasa/__init__.py
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/iot/iotbulb.py
  kasa/iot/iotplug.py
  kasa/iot/iotstrip.py
  kasa/tests/fixtures/smart/L530E(EU)_3.0_1.1.6.json
  kasa/tests/test_readme_examples.py
Labels: documentation

#921 Add post update hook to module and use in smart LightEffect
  kasa/module.py
  kasa/smart/modules/lighteffect.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/tests/test_smartdevice.py
Labels: enhancement

#929 Fix set_state for common light modules
  kasa/__init__.py
  kasa/interfaces/light.py
  kasa/iot/iotbulb.py
  kasa/iot/iotdimmer.py
  kasa/iot/modules/light.py
  kasa/smart/modules/light.py
  kasa/tests/test_bulb.py
  kasa/tests/test_common_modules.py
  kasa/tests/test_dimmer.py
Labels: enhancement

#924 Add state feature for iot devices
  kasa/device.py
  kasa/iot/iotdevice.py
Labels: enhancement

#935 Do not show a zero error code when cli exits from showing help
  kasa/cli.py
Labels: bug
