Repository python-kasa/python-kasa, pull requests merged in 2024-08, with the labels that each got.

#1086 Enable python 3.13, allow pre-releases for CI
  .github/actions/setup/action.yaml
  .github/workflows/ci.yml
  poetry.lock
Labels: maintenance

#1097 Improve performance of dict merge code
  kasa/iot/iotdevice.py
  kasa/iot/iotmodule.py
  kasa/tests/test_iotdevice.py
Labels: enhancement

#1098 Remove top level await xdoctest fixture
  kasa/tests/test_readme_examples.py
  poetry.lock
  pyproject.toml
Labels: maintenance

#1101 Add missing typing_extensions dependency
  poetry.lock
  pyproject.toml
Labels: maintenance

#1104 Add flake8-logging (LOG) and flake8-logging-format (G) for ruff
  kasa/aestransport.py
  kasa/device_factory.py
  kasa/discover.py
  kasa/emeterstatus.py
  kasa/iot/iotdevice.py
  kasa/klaptransport.py
  kasa/smart/modules/firmware.py
  kasa/smart/smartmodule.py
  kasa/smartprotocol.py
  kasa/tests/fakeprotocol_iot.py
  pyproject.toml
Labels: maintenance

#1107 Prepare 0.7.2
  CHANGELOG.md
  RELEASING.md
  poetry.lock
  pyproject.toml
Labels: release-prep
