Repository python-kasa/python-kasa, pull requests merged in 2024-04, with the labels that each got.

#764 Add fan module
  kasa/device_type.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/fanmodule.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  kasa/tests/smart/modules/test_fan.py
  kasa/tests/test_childdevice.py
Labels: enhancement

#829 smartbulb: Limit brightness range to 1-100
  kasa/smart/smartbulb.py
  kasa/tests/smart/features/test_brightness.py
  kasa/tests/test_smartdevice.py
Labels: bug

#840 Add ColorModule for smart devices
  kasa/smart/modules/__init__.py
  kasa/smart/modules/colormodule.py
  kasa/smart/modules/colortemp.py
  kasa/smart/smartbulb.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  kasa/tests/device_fixtures.py
  kasa/tests/smart/features/test_colortemp.py
  kasa/tests/test_bulb.py
Labels: enhancement

#850 Re-query missing responses after multi request errors
  kasa/smartprotocol.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/test_smartprotocol.py
Labels: enhancement

#848 Add temperature control module for smart
  kasa/device_type.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/temperaturecontrol.py
  kasa/smart/smartchilddevice.py
  kasa/tests/smart/modules/test_temperaturecontrol.py
Labels: enhancement

#857 Add rust tapo link to README
  README.md
Labels: documentation

#847 Add support for KH100 hub
  README.md
  SUPPORTED.md
  kasa/device_factory.py
  kasa/deviceconfig.py
  kasa/smart/modules/temperature.py
  kasa/smart/modules/temperaturecontrol.py
  kasa/tests/device_fixtures.py
  kasa/tests/fixtures/smart/KH100(UK)_1.0_1.5.6.json
  kasa/tests/fixtures/smart/child/KE100(EU)_1.0_2.8.0.json
  kasa/tests/fixtures/smart/child/KE100(UK)_1.0_2.8.0.json
  kasa/tests/fixtures/smart/child/T310(EU)_1.0_1.5.0.json
  kasa/tests/smart/modules/test_temperature.py
  kasa/tests/smart/modules/test_temperaturecontrol.py
Labels: enhancement

#854 Better firmware module support for devices not connected to the internet
  kasa/smart/modules/cloudmodule.py
  kasa/smart/modules/firmware.py
  kasa/smart/smartdevice.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/test_smartdevice.py
Labels: enhancement

#846 Implement feature categories
  kasa/cli.py
  kasa/device.py
  kasa/feature.py
  kasa/iot/iotbulb.py
  kasa/iot/iotdevice.py
  kasa/smart/modules/brightness.py
  kasa/smart/modules/colortemp.py
  kasa/smart/modules/fanmodule.py
  kasa/smart/modules/ledmodule.py
  kasa/smart/modules/reportmodule.py
  kasa/smart/modules/timemodule.py
  kasa/smart/smartdevice.py
Labels: enhancement

#849 Implement action feature
  kasa/feature.py
  kasa/smart/modules/alarmmodule.py
  kasa/tests/test_feature.py
Labels: enhancement

#839 Support for new ks240 fan/light wall switch
  README.md
  SUPPORTED.md
  kasa/smart/modules/brightness.py
  kasa/smart/modules/fanmodule.py
  kasa/smart/modules/lighttransitionmodule.py
  kasa/smart/smartdevice.py
  kasa/tests/device_fixtures.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/fixtures/smart/KS240(US)_1.0_1.0.4.json
  kasa/tests/fixtures/smart/KS240(US)_1.0_1.0.5.json
  kasa/tests/smart/features/test_brightness.py
  kasa/tests/smart/modules/test_fan.py
  kasa/tests/test_smartdevice.py
Labels: enhancement

#863 Be more lax on unknown SMART devices
  kasa/device_factory.py
  kasa/tests/test_device_factory.py
Labels: enhancement

#844 Expose IOT emeter info as features
  kasa/iot/iotstrip.py
  kasa/iot/modules/emeter.py
Labels: enhancement

#874 Move SmartBulb into SmartDevice
  kasa/__init__.py
  kasa/bulb.py
  kasa/cli.py
  kasa/device_factory.py
  kasa/smart/__init__.py
  kasa/smart/smartbulb.py
  kasa/smart/smartdevice.py
  kasa/tests/device_fixtures.py
  kasa/tests/test_bulb.py
  kasa/tests/test_childdevice.py
  kasa/tests/test_smartdevice.py
Labels: breaking change

#880 Implement choice feature type
  kasa/feature.py
  kasa/module.py
  kasa/smart/modules/alarmmodule.py
  kasa/smart/smartdevice.py
  kasa/tests/discovery_fixtures.py
  kasa/tests/test_cli.py
  kasa/tests/test_feature.py
Labels: enhancement

#876 Add support for waterleak sensor (T300)
  kasa/smart/modules/__init__.py
  kasa/smart/modules/waterleak.py
  kasa/smart/smartchilddevice.py
  kasa/tests/smart/modules/test_waterleak.py
Labels: enhancement

#886 Fix --help on subcommands
  kasa/cli.py
Labels: bug

#873 Add Fan interface for SMART devices
  kasa/fan.py
  kasa/smart/modules/fanmodule.py
  kasa/smart/smartdevice.py
  kasa/tests/smart/features/test_brightness.py
  kasa/tests/smart/modules/test_fan.py
  kasa/tests/test_smartdevice.py
Labels: enhancement
