Repository python-kasa/python-kasa, pull requests merged in 2024-03, with the labels that each got.

#758 Add WallSwitch device type and autogenerate supported devices docs
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  README.md
  SUPPORTED.md
  devtools/check_readme_vs_fixtures.py
  devtools/generate_supported.py
  docs/source/SUPPORTED.md
  docs/source/index.rst
  kasa/cli.py
  kasa/device.py
  kasa/device_factory.py
  kasa/device_type.py
  kasa/iot/__init__.py
  kasa/iot/iotplug.py
  kasa/smart/smartdevice.py
  kasa/tests/device_fixtures.py
  kasa/tests/test_device_factory.py
  kasa/tests/test_discovery.py
  kasa/tests/test_plug.py
  poetry.lock
  pyproject.toml
Labels: documentation

#806 Add brightness module
  kasa/smart/modules/__init__.py
  kasa/smart/modules/brightness.py
  kasa/smart/smartmodule.py
  kasa/tests/device_fixtures.py
  kasa/tests/test_feature_brightness.py
Labels: enhancement

#821 Add support for firmware module v1
  kasa/smart/modules/firmware.py
Labels: enhancement

#807 Revise device initialization and subsequent updates
  kasa/smart/modules/childdevicemodule.py
  kasa/smart/smartdevice.py
  kasa/tests/test_childdevice.py
  kasa/tests/test_smartdevice.py
Labels: enhancement

#814 Add colortemp module
  kasa/feature.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/colortemp.py
  kasa/tests/smart/features/__init__.py
  kasa/tests/smart/features/test_brightness.py
  kasa/tests/smart/features/test_colortemp.py
Labels: enhancement

#804 Change state_information to return feature values
  kasa/cli.py
  kasa/device.py
  kasa/iot/iotbulb.py
  kasa/iot/iotdevice.py
  kasa/iot/iotdimmer.py
  kasa/iot/iotlightstrip.py
  kasa/iot/iotplug.py
  kasa/iot/iotstrip.py
  kasa/smart/smartbulb.py
  kasa/smart/smartdevice.py
  kasa/tests/fakeprotocol_iot.py
  kasa/tests/test_bulb.py
  kasa/tests/test_lightstrip.py
Labels: breaking change

#827 Add colortemp feature for iot devices
  kasa/iot/iotbulb.py
  kasa/tests/test_bulb.py
Labels: enhancement
