Repository python-kasa/python-kasa, pull requests merged in 2024-09, with the labels that each got.

#986 Migrate from poetry to uv for dependency and package management
  .github/actions/setup/action.yaml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  README.md
  RELEASING.md
  devtools/run-in-env.sh
  docs/source/contribute.md
  poetry.lock
  pyproject.toml
  tox.ini
  uv.lock
Labels: maintenance

#1116 Prepare 0.7.3
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1124 Add reboot() to the device interface
  kasa/device.py
Labels: enhancement

#1108 Add factory-reset command to cli
  kasa/cli/device.py
  kasa/tests/test_cli.py
Labels: enhancement

#1123 Extend KL135 ct range up to 9000K
  kasa/iot/iotbulb.py
Labels: enhancement

#1129 Add fixture for T110 fw 1.9.0
  SUPPORTED.md
  kasa/tests/fixtures/smart/child/T110(EU)_1.0_1.9.0.json
Labels: maintenance

#1128 Speed up and simplify github workflows
  .github/actions/setup/action.yaml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  kasa/tests/test_device.py
  kasa/tests/test_protocol.py
  pyproject.toml
  uv.lock
Labels: maintenance

#1121 Fix cli command for device off
  kasa/cli/device.py
Labels: bug

#1125 Add factory_reset() to iotdevice
  kasa/device.py
  kasa/iot/iotdevice.py
Labels: enhancement

#1135 Prepare 0.7.4
  CHANGELOG.md
  RELEASING.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1140 Move feature initialization from __init__ to _initialize_features
  kasa/iot/modules/ambientlight.py
  kasa/iot/modules/cloud.py
  kasa/smart/modules/cloud.py
  kasa/smart/modules/color.py
  kasa/smart/modules/contactsensor.py
  kasa/smart/modules/fan.py
  kasa/smart/modules/humiditysensor.py
  kasa/smart/modules/reportmode.py
  kasa/smart/modules/temperaturesensor.py
  kasa/smart/modules/time.py
  kasa/smart/modules/waterleaksensor.py
Labels: maintenance

#1136 parse_pcap_klap: use request_uri for matching the response
  devtools/parse_pcap_klap.py
Labels: bug

#1137 parse_pcap_klap: require source host
  devtools/parse_pcap_klap.py
Labels: bug
