Repository python-kasa/python-kasa, pull requests merged in 2024-02, with the labels that each got.

#732 Avoid crashing on childdevice property accesses
  kasa/emeterstatus.py
  kasa/tapo/childdevice.py
  kasa/tapo/tapodevice.py
  kasa/tests/test_childdevice.py
Labels: bug

#734 Fix port-override for aes&klap transports
  kasa/aestransport.py
  kasa/cli.py
  kasa/httpclient.py
  kasa/klaptransport.py
  kasa/tests/test_aestransport.py
  kasa/tests/test_klapprotocol.py
Labels: bug

#735 Do not crash cli on missing discovery info
  kasa/cli.py
Labels: bug

#740 Reduce AuthenticationExceptions raising from transports
  kasa/aestransport.py
  kasa/klaptransport.py
  kasa/tests/test_klapprotocol.py
Labels: bug

#738 Add 'shell' command to cli
  kasa/cli.py
  kasa/tests/test_cli.py
  pyproject.toml
Labels: enhancement

#752 Ensure connections are closed when cli is finished
  kasa/cli.py
  kasa/device_factory.py
  kasa/tests/test_device_factory.py
Labels: bug

#751 Fix for P100 on fw 1.1.3 login_version none
  kasa/aestransport.py
  kasa/smart/smartdevice.py
  kasa/smartprotocol.py
  kasa/tests/test_aestransport.py
Labels: bug

#741 Add generic interface for accessing device features
  kasa/__init__.py
  kasa/cli.py
  kasa/device.py
  kasa/feature.py
  kasa/iot/iotdevice.py
  kasa/iot/iotplug.py
  kasa/iot/modules/cloud.py
  kasa/iot/modules/module.py
  kasa/smart/smartdevice.py
  kasa/tests/test_cli.py
  kasa/tests/test_feature.py
  kasa/tests/test_smartdevice.py
Labels: enhancement, breaking change

#754 Let caller handle SMART errors on multi-requests
  kasa/exceptions.py
  kasa/smart/smartdevice.py
  kasa/smartprotocol.py
  kasa/tests/test_smartdevice.py
  kasa/tests/test_smartprotocol.py
Labels: enhancement

#759 Add smartdevice module for smooth transitions
  kasa/smart/modules/__init__.py
  kasa/smart/modules/lighttransitionmodule.py
  kasa/smart/smartdevice.py
  kasa/tests/fakeprotocol_smart.py
Labels: enhancement

#767 Add cloud module for smartdevice
  kasa/smart/modules/__init__.py
  kasa/smart/modules/cloudmodule.py
  kasa/tests/fakeprotocol_smart.py
Labels: enhancement

#761 Add smartdevice module for led controls
  kasa/smart/modules/__init__.py
  kasa/smart/modules/ledmodule.py
  kasa/smart/smartdevice.py
  kasa/tests/fakeprotocol_smart.py
Labels: enhancement

#760 Auto auto-off module for smartdevice
  kasa/feature.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/autooffmodule.py
  kasa/smart/smartdevice.py
  kasa/tests/fakeprotocol_smart.py
Labels: enhancement

#766 Add firmware module for smartdevice
  kasa/smart/modules/__init__.py
  kasa/smart/modules/firmware.py
Labels: enhancement

#771 Raise CLI errors in debug mode
  kasa/cli.py
  kasa/tests/test_cli.py
Labels: enhancement

#782 Enable shell extra for installing ptpython and rich
  .github/workflows/ci.yml
  README.md
  kasa/tests/test_cli.py
  poetry.lock
  pyproject.toml
Labels: documentation

#739 Rename and deprecate exception classes
  devtools/dump_devinfo.py
  docs/source/design.rst
  docs/source/smartdevice.rst
  kasa/__init__.py
  kasa/aestransport.py
  kasa/cli.py
  kasa/device.py
  kasa/device_factory.py
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/exceptions.py
  kasa/httpclient.py
  kasa/iot/iotbulb.py
  kasa/iot/iotdevice.py
  kasa/iot/iotdimmer.py
  kasa/iot/iotlightstrip.py
  kasa/iot/iotmodule.py
  kasa/iot/iotplug.py
  kasa/iot/iotstrip.py
  kasa/iot/modules/motion.py
  kasa/iot/modules/time.py
  kasa/iotprotocol.py
  kasa/klaptransport.py
  kasa/module.py
  kasa/smart/smartbulb.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  kasa/smartprotocol.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/test_aestransport.py
  kasa/tests/test_bulb.py
  kasa/tests/test_cli.py
  kasa/tests/test_device_factory.py
  kasa/tests/test_deviceconfig.py
  kasa/tests/test_discovery.py
  kasa/tests/test_emeter.py
  kasa/tests/test_httpclient.py
  kasa/tests/test_klapprotocol.py
  kasa/tests/test_lightstrip.py
  kasa/tests/test_protocol.py
  kasa/tests/test_smartdevice.py
  kasa/tests/test_smartprotocol.py
  kasa/tests/test_strip.py
  kasa/xortransport.py
Labels: breaking change

#781 Remove SmartPlug in favor of SmartDevice
  kasa/__init__.py
  kasa/cli.py
  kasa/device.py
  kasa/device_factory.py
  kasa/smart/__init__.py
  kasa/smart/smartdevice.py
  kasa/smart/smartplug.py
  kasa/tests/conftest.py
  kasa/tests/test_plug.py
  kasa/tests/test_smartdevice.py
Labels: breaking change

#785 Retry query on 403 after successful handshake
  kasa/klaptransport.py
  kasa/tests/test_klapprotocol.py
Labels: bug

#787 Add feature for ambient light sensor
  devtools/helpers/smartrequests.py
  kasa/iot/modules/ambientlight.py
Labels: enhancement

#775 Generalize smartdevice child support
  kasa/cli.py
  kasa/device.py
  kasa/device_type.py
  kasa/iot/iotdevice.py
  kasa/iot/iotstrip.py
  kasa/smart/modules/childdevicemodule.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  kasa/tests/test_childdevice.py
  kasa/tests/test_cli.py
  kasa/tests/test_smartdevice.py
Labels: enhancement

#786 Fix auto update switch
  kasa/smart/modules/firmware.py
Labels: bug

#776 Add initial support for H100 and T315
  kasa/cli.py
  kasa/device_factory.py
  kasa/device_type.py
  kasa/deviceconfig.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/alarmmodule.py
  kasa/smart/modules/battery.py
  kasa/smart/modules/humidity.py
  kasa/smart/modules/reportmodule.py
  kasa/smart/modules/temperature.py
  kasa/smart/smartbulb.py
  kasa/smart/smartdevice.py
  kasa/tests/conftest.py
  kasa/tests/test_childdevice.py
Labels: enhancement

#789 Add --child option to feature command
  kasa/cli.py
  kasa/tests/conftest.py
  kasa/tests/test_cli.py
Labels: enhancement

#793 Support for on_off_gradually v2+
  kasa/feature.py
  kasa/smart/modules/devicemodule.py
  kasa/smart/modules/lighttransitionmodule.py
  kasa/smart/smartmodule.py
Labels: enhancement

#795 Support multiple child requests
  kasa/smartprotocol.py
  kasa/tests/test_smartprotocol.py
Labels: enhancement

#798 Fix energy module calling get_current_power
  kasa/smart/modules/energymodule.py
Labels: bug
