Repository python-kasa/python-kasa, pull requests merged in 2024-01, with the labels that each got.

#594 Add support for KS205 and KS225 wall switches
  README.md
  kasa/device_factory.py
  kasa/deviceconfig.py
  kasa/tapo/tapobulb.py
  kasa/tests/conftest.py
  kasa/tests/fixtures/smart/KS205(US)_1.0_1.0.2.json
  kasa/tests/fixtures/smart/KS225(US)_1.0_1.0.2.json
  kasa/tests/test_bulb.py
Labels: enhancement

#606 Implement wifi interface for tapodevice
  kasa/cli.py
  kasa/smartdevice.py
  kasa/tapo/tapodevice.py
Labels: enhancement

#607 Allow serializing and passing of credentials_hashes in DeviceConfig
  kasa/aestransport.py
  kasa/cli.py
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/klaptransport.py
  kasa/protocol.py
  kasa/smartdevice.py
  kasa/tapo/tapodevice.py
  kasa/tests/conftest.py
  kasa/tests/newfakes.py
  kasa/tests/test_deviceconfig.py
  kasa/tests/test_discovery.py
  kasa/tests/test_protocol.py
Labels: enhancement

#615 Fix cli discover bug with None username/password
  kasa/aestransport.py
  kasa/cli.py
  kasa/klaptransport.py
Labels: bug

#619 Check the ct range for color temp support
  kasa/tapo/tapobulb.py
Labels: bug

#622 Avoid linear search for emeter realtime and emeter_today
  kasa/modules/emeter.py
  kasa/modules/usage.py
  kasa/tests/test_emeter.py
  kasa/tests/test_usage.py
Labels: enhancement

#620 Add update-credentials command
  kasa/cli.py
  kasa/tapo/tapodevice.py
Labels: enhancement

#623 Get child emeters with CLI
  kasa/cli.py
  kasa/device_factory.py
  kasa/tests/test_cli.py
Labels: enhancement

#614 Update docs for newer devices and DeviceConfig
  .gitignore
  docs/source/cli.rst
  docs/source/conf.py
  docs/source/deviceconfig.rst
  docs/source/discover.rst
  docs/source/index.rst
  docs/source/smartbulb.rst
  docs/source/smartdevice.rst
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/smartdevice.py
Labels: documentation

#636 Fix connection indeterminate state on cancellation
  kasa/protocol.py
  kasa/tests/test_protocol.py
Labels: bug

#655 Fix httpclient exceptions on read and improve error info
  kasa/exceptions.py
  kasa/httpclient.py
  kasa/tests/test_httpclient.py
Labels: bug

#663 Add protocol and transport documentation
  docs/source/design.rst
  kasa/protocol.py
Labels: documentation

#656 Sleep between discovery packets
  kasa/discover.py
  kasa/tests/test_discovery.py
Labels: enhancement

#686 Add reboot and factory_reset to tapodevice
  kasa/tapo/tapodevice.py
  kasa/tests/test_cli.py
Labels: enhancement

#685 Try default tapo credentials for klap and aes
  kasa/aestransport.py
  kasa/klaptransport.py
  kasa/protocol.py
  kasa/tests/test_aestransport.py
  kasa/tests/test_klapprotocol.py
Labels: enhancement

#687 Generate AES KeyPair lazily
  kasa/aestransport.py
  kasa/httpclient.py
  kasa/json.py
  kasa/tests/test_aestransport.py
Labels: enhancement

#688 Allow raw-command and wifi without update
  kasa/cli.py
  kasa/tests/test_cli.py
Labels: enhancement

#701 Do not crash on missing geolocation
  kasa/tapo/tapodevice.py
Labels: bug

#634 Document authenticated provisioning
  docs/source/cli.rst
Labels: documentation

#704 Add support for tapo wall switches (S500D)
  README.md
  kasa/device_factory.py
  kasa/deviceconfig.py
  kasa/tests/conftest.py
  kasa/tests/fixtures/smart/S500D(US)_1.0_1.0.5.json
Labels: enhancement

#721 Implement alias set for tapodevice
  kasa/tapo/tapodevice.py
Labels: enhancement

#715 Avoid rebuilding urls for every request
  kasa/aestransport.py
  kasa/exceptions.py
  kasa/httpclient.py
  kasa/klaptransport.py
  kasa/tests/test_aestransport.py
  kasa/tests/test_httpclient.py
  kasa/tests/test_klapprotocol.py
Labels: enhancement

#720 Initial support for tapos with child devices
  kasa/smartprotocol.py
  kasa/tapo/childdevice.py
  kasa/tapo/tapodevice.py
  kasa/tapo/tapoplug.py
  kasa/tests/test_protocol.py
  kasa/tests/test_smartprotocol.py
Labels: enhancement
