Repository python-kasa/python-kasa, pull requests merged in 2024-10, with the labels that each got.

#1145 Send empty dictionary instead of null for iot queries
  devtools/dump_devinfo.py
  kasa/device_factory.py
  kasa/discover.py
  kasa/iot/iotdevice.py
  kasa/klaptransport.py
Labels: bug

#1144 Stabilise on_since value for smart devices
  kasa/device.py
  kasa/iot/iotdevice.py
  kasa/iot/iotstrip.py
  kasa/smart/smartdevice.py
Labels: bug

#1146 Remove async magic patch from tests
  kasa/tests/conftest.py
  kasa/tests/test_device.py
  kasa/tests/test_feature.py
  kasa/tests/test_protocol.py
Labels: maintenance

#1147 Make iot time timezone aware
  kasa/cli/device.py
  kasa/device.py
  kasa/iot/iotdevice.py
  kasa/iot/iotstrip.py
  kasa/iot/iottimezone.py
  kasa/iot/modules/emeter.py
  kasa/iot/modules/light.py
  kasa/iot/modules/lightpreset.py
  kasa/iot/modules/time.py
  kasa/module.py
  kasa/smart/modules/devicemodule.py
  kasa/smart/modules/light.py
  kasa/smart/modules/lighteffect.py
  kasa/smart/modules/lightpreset.py
  kasa/smart/modules/lighttransition.py
  kasa/smart/modules/time.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  kasa/tests/test_device.py
  pyproject.toml
  uv.lock
Labels: enhancement, breaking change

#1160 Prepare 0.7.5
  .github_changelog_generator
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1157 Create common Time module and add time set cli command
  kasa/cli/common.py
  kasa/cli/time.py
  kasa/device.py
  kasa/interfaces/__init__.py
  kasa/interfaces/time.py
  kasa/iot/iotbulb.py
  kasa/iot/iotdevice.py
  kasa/iot/iotplug.py
  kasa/iot/iotstrip.py
  kasa/iot/iottimezone.py
  kasa/iot/modules/time.py
  kasa/module.py
  kasa/smart/modules/time.py
  kasa/tests/fakeprotocol_iot.py
  kasa/tests/test_cli.py
  kasa/tests/test_common_modules.py
  kasa/tests/test_device.py
  kasa/tests/test_iotdevice.py
Labels: enhancement

#1165 Initial TapoCamera support
  kasa/cli/main.py
  kasa/device_factory.py
  kasa/device_type.py
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/experimental/__init__.py
  kasa/experimental/enabled.py
  kasa/experimental/smartcamera.py
  kasa/experimental/smartcameraprotocol.py
  kasa/experimental/sslaestransport.py
  kasa/httpclient.py
  kasa/tests/test_cli.py
  pyproject.toml
Labels: enhancement

#1169 Update dump_devinfo for smart camera protocol
  devtools/dump_devinfo.py
  devtools/helpers/smartrequests.py
  kasa/experimental/smartcameraprotocol.py
  kasa/experimental/sslaestransport.py
  kasa/smartprotocol.py
  kasa/tests/fixtures/experimental/C210(EU)_2.0_1.4.2.json
Labels: enhancement

#1162 Add waterleak alert timestamp
  kasa/smart/modules/waterleaksensor.py
  kasa/tests/fixtures/smart/child/T300(EU)_1.0_1.7.0.json
  kasa/tests/smart/modules/test_waterleak.py
Labels: enhancement

#1177 Convert fixtures to use unix newlines
  .gitattributes
  kasa/tests/fixtures/KL135(US)_1.0_1.0.15.json
  kasa/tests/fixtures/smart/S505D(US)_1.0_1.1.0.json
  kasa/tests/fixtures/smart/child/T100(EU)_1.0_1.12.0.json
  kasa/tests/fixtures/smart/child/T110(EU)_1.0_1.8.0.json
Labels: maintenance

#1178 Enforce EOLs for *.rst and *.md
  .gitattributes
Labels: maintenance

#1183 Add discovery list command to cli
  kasa/cli/discover.py
  kasa/tests/test_cli.py
Labels: enhancement

#1171 Add try_connect_all to allow initialisation without udp broadcast
  kasa/cli/discover.py
  kasa/cli/main.py
  kasa/discover.py
  kasa/tests/test_cli.py
  kasa/tests/test_discovery.py
Labels: enhancement

#1184 Add https parameter to device class factory
  kasa/cli/discover.py
  kasa/device_factory.py
  kasa/discover.py
  kasa/exceptions.py
  kasa/tests/discovery_fixtures.py
  kasa/tests/test_cli.py
  kasa/tests/test_device_factory.py
  kasa/tests/test_discovery.py
Labels: enhancement

#1188 Improve supported module checks for hub children
  kasa/smart/modules/devicemodule.py
  kasa/smart/modules/time.py
  kasa/smart/smartdevice.py
  kasa/tests/test_childdevice.py
Labels: maintenance

#1192 Add test framework for smartcamera
  kasa/experimental/smartcamera.py
  kasa/tests/device_fixtures.py
  kasa/tests/fakeprotocol_smartcamera.py
  kasa/tests/fixtureinfo.py
  kasa/tests/smartcamera/__init__.py
  kasa/tests/smartcamera/test_smartcamera.py
Labels: maintenance

#1187 Update smartcamera to support single get/set/do requests
  devtools/dump_devinfo.py
  devtools/helpers/smartcamerarequests.py
  kasa/experimental/smartcameraprotocol.py
  kasa/smartprotocol.py
  kasa/tests/fakeprotocol_smartcamera.py
  kasa/tests/fixtures/smartcamera/C210(EU)_2.0_1.4.2.json
  kasa/tests/fixtures/smartcamera/H200(US)_1.0_1.3.6.json
Labels: maintenance

#1182 Add Time module to SmartCamera devices
  kasa/experimental/modules/__init__.py
  kasa/experimental/modules/time.py
  kasa/experimental/smartcameramodule.py
  kasa/tests/fakeprotocol_smartcamera.py
  kasa/tests/smartcamera/test_smartcamera.py
Labels: enhancement

#1196 Fix device_config serialisation of https value
  kasa/deviceconfig.py
Labels: bug

#1195 Try default logon credentials in SslAesTransport
  kasa/exceptions.py
  kasa/experimental/sslaestransport.py
  kasa/protocol.py
Labels: enhancement

#1199 Update SMART test framework to use fake child protocols
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/fakeprotocol_smartcamera.py
  kasa/tests/fixtureinfo.py
  kasa/tests/test_emeter.py
Labels: maintenance

#1185 Add P304M(UK) test fixture
  README.md
  SUPPORTED.md
  kasa/tests/device_fixtures.py
  kasa/tests/fixtures/smart/P304M(UK)_1.0_1.0.3.json
Labels: new device

#1202 Fix SslAesTransport default login and add tests
  kasa/experimental/sslaestransport.py
  kasa/tests/test_sslaestransport.py
Labels: bug

#1194 Allow enabling experimental devices from environment variable
  devtools/dump_devinfo.py
  kasa/cli/main.py
  kasa/device_factory.py
  kasa/experimental/__init__.py
  kasa/experimental/enabled.py
  kasa/tests/test_cli.py
Labels: enhancement

#1161 Add S200D button fixtures
  README.md
  SUPPORTED.md
  kasa/tests/device_fixtures.py
  kasa/tests/fixtures/smart/child/S200D(EU)_1.0_1.11.0.json
  kasa/tests/fixtures/smart/child/S200D(EU)_1.0_1.12.0.json
Labels: new device

#1181 Add S200B(US) fw 1.12.0 fixture
  SUPPORTED.md
  kasa/tests/fixtures/smart/child/S200B(US)_1.0_1.12.0.json
Labels: maintenance

#1207 Only send 20002 discovery request with key included
  kasa/discover.py
  kasa/tests/test_discovery.py
Labels: bug

#1214 Fix mypy errors in parse_pcap_klap
  devtools/parse_pcap_klap.py
Labels: maintenance

#1213 Prepare 0.7.6
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1174 Expose PIR enabled setting for iot dimmers
  kasa/iot/modules/motion.py
  kasa/tests/iot/modules/__init__.py
  kasa/tests/iot/modules/test_motion.py
Labels: enhancement

#1210 Expose ambient light setting for iot dimmers
  kasa/iot/modules/ambientlight.py
  kasa/tests/iot/modules/test_ambientlight.py
Labels: enhancement
