Repository python-kasa/python-kasa, pull requests merged in 2024-11, with the labels that each got.

#900 Initial trigger logs implementation
  kasa/cli/device.py
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/triggerlogs.py
Labels: enhancement, no-stale

#1141 Add childprotection module
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/childprotection.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/smart/modules/test_childprotection.py
Labels: enhancement

#1227 Add PIR&LAS for wall switches mentioning PIR support
  kasa/iot/iotplug.py
  kasa/tests/iot/test_wallswitch.py
Labels: enhancement

#1138 parse_pcap_klap: various code cleanups
  devtools/parse_pcap_klap.py
Labels: maintenance

#1229 Prepare 0.7.7
  CHANGELOG.md
  RELEASING.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1233 Make __repr__ work on discovery info
  kasa/device.py
  kasa/smart/smartdevice.py
  kasa/tests/test_discovery.py
Labels: bug

#1238 Add EP40M Fixture
  README.md
  SUPPORTED.md
  kasa/tests/device_fixtures.py
  kasa/tests/fixtures/smart/EP40M(US)_1.0_1.1.0.json
Labels: new device

#1237 Add KS220 Fixture
  README.md
  SUPPORTED.md
  kasa/tests/device_fixtures.py
  kasa/tests/fixtures/KS220(US)_1.0_1.0.13.json
Labels: new device

#1216 Print formatting for IotLightPreset
  kasa/cli/light.py
Labels: enhancement

#1240 Add L630 fixture
  README.md
  SUPPORTED.md
  kasa/tests/fixtures/smart/L630(EU)_1.0_1.1.2.json
Labels: new device

#1236 Fixup contributing.md for running test against a real device
  docs/source/contribute.md
Labels: documentation

#1215 Update fixture for ES20M 1.0.11
  kasa/tests/fixtures/ES20M(US)_1.0_1.0.11.json
  kasa/tests/test_dimmer.py
Labels: maintenance

#1235 Fix test framework running against real devices
  kasa/device.py
  kasa/iot/iotdevice.py
  kasa/smart/smartdevice.py
  tests/device_fixtures.py
  tests/fixtureinfo.py
  tests/smart/modules/test_firmware.py
  tests/test_aestransport.py
  tests/test_bulb.py
  tests/test_childdevice.py
  tests/test_cli.py
  tests/test_common_modules.py
  tests/test_device_factory.py
  tests/test_discovery.py
  tests/test_klapprotocol.py
  tests/test_protocol.py
  tests/test_smartdevice.py
  tests/test_smartprotocol.py
  tests/test_sslaestransport.py
Labels: maintenance

#1247 Move transports into their own package
  devtools/parse_pcap.py
  devtools/parse_pcap_klap.py
  docs/source/reference.md
  kasa/__init__.py
  kasa/device.py
  kasa/device_factory.py
  kasa/discover.py
  kasa/experimental/sslaestransport.py
  kasa/iotprotocol.py
  kasa/protocol.py
  kasa/smart/smartdevice.py
  kasa/smartprotocol.py
  kasa/transports/__init__.py
  kasa/transports/aestransport.py
  kasa/transports/basetransport.py
  kasa/transports/klaptransport.py
  kasa/transports/xortransport.py
  tests/conftest.py
  tests/discovery_fixtures.py
  tests/fakeprotocol_iot.py
  tests/fakeprotocol_smart.py
  tests/fakeprotocol_smartcamera.py
  tests/test_aestransport.py
  tests/test_discovery.py
  tests/test_klapprotocol.py
  tests/test_protocol.py
  tests/test_sslaestransport.py
Labels: maintenance

#1249 Add SmartCamera Led Module
  kasa/experimental/modules/__init__.py
  kasa/experimental/modules/led.py
Labels: enhancement

#1231 Update DiscoveryResult to use Mashumaro instead of pydantic
  devtools/dump_devinfo.py
  kasa/cli/discover.py
  kasa/discover.py
  kasa/json.py
  pyproject.toml
  tests/test_cli.py
  tests/test_device_factory.py
  tests/test_discovery.py
  uv.lock
Labels: maintenance

#1250 Update smartcamera fixtures with components
  tests/fixtures/smartcamera/C210(EU)_2.0_1.4.2.json
  tests/fixtures/smartcamera/H200(EU)_1.0_1.3.2.json
  tests/fixtures/smartcamera/H200(US)_1.0_1.3.6.json
Labels: maintenance

#1248 Use component queries to select smartcamera modules
  kasa/experimental/modules/childdevice.py
  kasa/experimental/smartcamera.py
  kasa/experimental/smartcameramodule.py
Labels: enhancement

#1246 Fix warnings in our test suite
  kasa/device.py
  tests/fakeprotocol_smart.py
  tests/smart/modules/test_contact.py
  tests/smart/modules/test_light_effect.py
  tests/smart/modules/test_light_strip_effect.py
  tests/smart/modules/test_motionsensor.py
  tests/test_bulb.py
  tests/test_device.py
  tests/test_dimmer.py
  tests/test_discovery.py
  tests/test_emeter.py
  tests/test_iotdevice.py
  tests/test_lightstrip.py
  tests/test_plug.py
  tests/test_smartdevice.py
  tests/test_smartprotocol.py
Labels: maintenance

#1253 Add linkcheck to readthedocs CI
  .readthedocs.yml
  README.md
  docs/source/contribute.md
Labels: maintenance

#1254 Move protocol modules into protocols package
  devtools/dump_devinfo.py
  devtools/parse_pcap_klap.py
  docs/source/reference.md
  docs/source/topics.md
  kasa/__init__.py
  kasa/credentials.py
  kasa/device.py
  kasa/device_factory.py
  kasa/discover.py
  kasa/experimental/smartcameraprotocol.py
  kasa/experimental/sslaestransport.py
  kasa/iot/iotbulb.py
  kasa/iot/iotdevice.py
  kasa/iot/iotdimmer.py
  kasa/iot/iotlightstrip.py
  kasa/iot/iotplug.py
  kasa/iot/iotstrip.py
  kasa/protocols/__init__.py
  kasa/protocols/iotprotocol.py
  kasa/protocols/protocol.py
  kasa/protocols/smartprotocol.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/transports/aestransport.py
  kasa/transports/klaptransport.py
  tests/fakeprotocol_iot.py
  tests/test_childdevice.py
  tests/test_klapprotocol.py
  tests/test_protocol.py
  tests/test_smartdevice.py
  tests/test_smartprotocol.py
  tests/test_sslaestransport.py
Labels: maintenance

#1255 Move TAPO smartcamera out of experimental package
  devtools/dump_devinfo.py
  kasa/device_factory.py
  kasa/module.py
  kasa/protocols/smartcameraprotocol.py
  kasa/smartcamera/__init__.py
  kasa/smartcamera/modules/__init__.py
  kasa/smartcamera/modules/camera.py
  kasa/smartcamera/modules/childdevice.py
  kasa/smartcamera/modules/device.py
  kasa/smartcamera/modules/led.py
  kasa/smartcamera/modules/time.py
  kasa/smartcamera/smartcamera.py
  kasa/smartcamera/smartcameramodule.py
  kasa/transports/sslaestransport.py
  tests/device_fixtures.py
  tests/discovery_fixtures.py
  tests/fakeprotocol_smartcamera.py
  tests/fixtureinfo.py
  tests/test_cli.py
  tests/test_device_factory.py
  tests/test_sslaestransport.py
Labels: enhancement

#1257 Add smartcamera devices to supported docs
  README.md
  SUPPORTED.md
  devtools/dump_devinfo.py
  devtools/generate_supported.py
  kasa/device.py
  kasa/smartcamera/smartcamera.py
Labels: new device

#1258 Add alarm module for smartcamera hubs
  kasa/smartcamera/modules/__init__.py
  kasa/smartcamera/modules/alarm.py
  kasa/smartcamera/smartcameramodule.py
  tests/fakeprotocol_smartcamera.py
  tests/smartcamera/modules/__init__.py
  tests/smartcamera/modules/test_alarm.py
Labels: enhancement

#1260 Fix discovery by alias for smart devices
  kasa/cli/discover.py
  kasa/cli/main.py
Labels: bug

#1266 Fix repr for device created with no sysinfo or discovery info"
  kasa/device.py
  kasa/iot/iotdevice.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smartcamera/smartcamera.py
  tests/test_childdevice.py
  tests/test_device.py
Labels: bug

#1265 Use _get_device_info methods for smart and iot devs in devtools
  SUPPORTED.md
  devtools/dump_devinfo.py
  devtools/generate_supported.py
  kasa/device.py
  kasa/device_factory.py
  kasa/iot/iotdevice.py
  kasa/smart/smartdevice.py
  kasa/smartcamera/smartcamera.py
  tests/conftest.py
  tests/device_fixtures.py
  tests/fakeprotocol_iot.py
  tests/fakeprotocol_smart.py
  tests/fakeprotocol_smartcamera.py
  tests/fixtureinfo.py
  tests/fixtures/smart/P100(US)_1.0.0_1.1.3.json
  tests/fixtures/smart/P100(US)_1.0.0_1.3.7.json
  tests/fixtures/smart/P100(US)_1.0.0_1.4.0.json
  tests/test_device_factory.py
  tests/test_devtools.py
  tests/test_discovery.py
Labels: maintenance

#1272 Allow callable coroutines for feature setters
  kasa/feature.py
Labels: maintenance

#1261 Add pan tilt camera module
  kasa/smartcamera/modules/__init__.py
  kasa/smartcamera/modules/pantilt.py
  tests/test_feature.py
Labels: enhancement

#1280 Update sphinx dependency to 6.2 to fix docs build
  pyproject.toml
  uv.lock
Labels: maintenance

#1279 Update DiscoveryResult to use mashu Annotated Alias
  kasa/discover.py
Labels: maintenance

#1278 Extend dump_devinfo iot queries
  devtools/dump_devinfo.py
  tests/fakeprotocol_iot.py
  tests/fixtures/KP105(UK)_1.0_1.0.5.json
Labels: maintenance

#1274 Replace custom deviceconfig serialization with mashumaru
  kasa/deviceconfig.py
  tests/conftest.py
  tests/fixtures/serialization/deviceconfig_camera-aes-https.json
  tests/fixtures/serialization/deviceconfig_plug-klap.json
  tests/fixtures/serialization/deviceconfig_plug-xor.json
  tests/test_deviceconfig.py
Labels: breaking change

#1275 Migrate IotLightPreset to mashumaru
  kasa/iot/iotbulb.py
  kasa/iot/modules/lightpreset.py
Labels: maintenance

#1276 Migrate smart firmware module to mashumaro
  kasa/smart/modules/firmware.py
  tests/smart/modules/test_firmware.py
Labels: maintenance

#1284 dump_devinfo: query smartlife.iot.common.cloud for fw updates
  devtools/dump_devinfo.py
  tests/fixtures/KL130(EU)_1.0_1.8.8.json
Labels: maintenance

#1277 Migrate triggerlogs to mashumaru
  kasa/smart/modules/triggerlogs.py
  tests/smart/modules/test_triggerlogs.py
Labels: maintenance

#1282 Migrate iot cloud module to mashumaro
  kasa/iot/modules/cloud.py
  tests/fakeprotocol_iot.py
  tests/iot/modules/test_cloud.py
Labels: breaking change

#1285 Migrate TurnOnBehaviours to mashumaro
  kasa/iot/iotbulb.py
  tests/fakeprotocol_iot.py
  tests/test_bulb.py
Labels: maintenance

#1287 Do not print out all the fixture names at the start of test runs
  tests/fixtureinfo.py
Labels: maintenance

#1283 Migrate RuleModule to mashumaro
  kasa/iot/iotdevice.py
  kasa/iot/modules/rulemodule.py
  tests/fakeprotocol_iot.py
  tests/iot/modules/test_schedule.py
Labels: maintenance

#1289 Remove pydantic dependency
  kasa/cli/discover.py
  pyproject.toml
  uv.lock
Labels: maintenance

#1290 Add SMART Voltage Monitoring to Fixtures
  devtools/helpers/smartrequests.py
  tests/fixtures/smart/KP125M(US)_1.0_1.2.3.json
Labels: maintenance

#1295 Update cli modify presets to support smart devices
  kasa/cli/light.py
  tests/test_cli.py
Labels: enhancement

#1291 Make discovery on unsupported devices less noisy
  kasa/device_factory.py
  kasa/discover.py
  tests/discovery_fixtures.py
  tests/test_device_factory.py
Labels: bug

#1293 Use credentials_hash for smartcamera rtsp url
  kasa/smartcamera/modules/camera.py
  tests/smartcamera/test_smartcamera.py
Labels: enhancement

#1294 Exclude __getattr__ for deprecated attributes from type checkers
  kasa/__init__.py
  kasa/cli/light.py
  kasa/device.py
  kasa/interfaces/energy.py
  kasa/iot/iotdimmer.py
  kasa/iot/iotmodule.py
  kasa/iot/iotstrip.py
  kasa/iot/modules/light.py
  kasa/smart/smartdevice.py
  tests/test_emeter.py
Labels: maintenance

#1018 Allow getting Annotated features from modules
  kasa/module.py
  kasa/smart/modules/fan.py
  tests/smart/modules/test_fan.py
Labels: enhancement, no-stale

#1298 Annotate fan_speed_level of Fan interface
  kasa/interfaces/fan.py
Labels: maintenance

#1300 Rename smartcamera to smartcam
  devtools/dump_devinfo.py
  devtools/generate_supported.py
  devtools/helpers/smartcamrequests.py
  kasa/device_factory.py
  kasa/module.py
  kasa/protocols/smartcamprotocol.py
  kasa/protocols/smartprotocol.py
  kasa/smartcam/__init__.py
  kasa/smartcam/modules/__init__.py
  kasa/smartcam/modules/alarm.py
  kasa/smartcam/modules/camera.py
  kasa/smartcam/modules/childdevice.py
  kasa/smartcam/modules/device.py
  kasa/smartcam/modules/led.py
  kasa/smartcam/modules/pantilt.py
  kasa/smartcam/modules/time.py
  kasa/smartcam/smartcamdevice.py
  kasa/smartcam/smartcammodule.py
  kasa/smartcamera/__init__.py
  tests/device_fixtures.py
  tests/discovery_fixtures.py
  tests/fakeprotocol_smartcam.py
  tests/fixtureinfo.py
  tests/fixtures/smartcam/C210(EU)_2.0_1.4.2.json
  tests/fixtures/smartcam/C210(EU)_2.0_1.4.3.json
  tests/fixtures/smartcam/H200(EU)_1.0_1.3.2.json
  tests/fixtures/smartcam/H200(US)_1.0_1.3.6.json
  tests/fixtures/smartcam/TC65_1.0_1.3.9.json
  tests/smartcamera/modules/test_alarm.py
  tests/smartcamera/test_smartcamera.py
  tests/test_cli.py
  tests/test_device.py
  tests/test_device_factory.py
  tests/test_devtools.py
Labels: maintenance

#1244 Add P110M(AU) fixture
  README.md
  SUPPORTED.md
  tests/device_fixtures.py
  tests/fixtures/smart/P110M(AU)_1.0_1.2.3.json
Labels: new device

#1303 Add HS200 (US) Smart Fixture
  README.md
  SUPPORTED.md
  tests/device_fixtures.py
  tests/fixtures/smart/HS200(US)_5.26_1.0.3.json
Labels: new device

#1305 Add P110M(EU) fixture
  SUPPORTED.md
  tests/fixtures/smart/P110M(EU)_1.0_1.2.3.json
Labels: maintenance

#1301 Update docs for the new module attributes has/get feature
  kasa/interfaces/light.py
  kasa/module.py
  kasa/smart/modules/light.py
  pyproject.toml
  uv.lock
Labels: documentation

#1307 Expose energy command to cli
  kasa/cli/main.py
  kasa/cli/usage.py
  kasa/smart/modules/energy.py
  tests/test_cli.py
  tests/test_emeter.py
Labels: bug

#1313 Include duration when disabling smooth transition on/off
  kasa/smart/modules/lighttransition.py
Labels: bug

#1315 Rename tests/smartcamera to tests/smartcam
  tests/smartcam/__init__.py
  tests/smartcam/modules/__init__.py
  tests/smartcam/modules/test_alarm.py
  tests/smartcam/test_smartcamera.py
Labels: maintenance

#1312 Prepare 0.8.0
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1317 Follow main package structure for tests
  tests/device_fixtures.py
  tests/iot/modules/test_emeter.py
  tests/iot/modules/test_usage.py
  tests/iot/test_iotbulb.py
  tests/iot/test_iotdevice.py
  tests/iot/test_iotdimmer.py
  tests/iot/test_iotlightstrip.py
  tests/protocols/__init__.py
  tests/protocols/test_iotprotocol.py
  tests/protocols/test_smartprotocol.py
  tests/smart/modules/test_energy.py
  tests/smart/test_smartdevice.py
  tests/test_bulb.py
  tests/test_plug.py
  tests/transports/__init__.py
  tests/transports/test_aestransport.py
  tests/transports/test_klaptransport.py
  tests/transports/test_sslaestransport.py
Labels: maintenance

#1318 Handle missing mgt_encryption_schm in discovery
  kasa/cli/discover.py
  kasa/discover.py
  tests/discovery_fixtures.py
Labels: maintenance

#1326 Remove unnecessary check for python <3.10
  tests/smart/modules/test_autooff.py
Labels: maintenance
