Repository python-kasa/python-kasa, pull requests merged in 2024-07, with the labels that each got.

#1025 Disable multi requests on json decode error during multi-request
  kasa/smartprotocol.py
  kasa/tests/test_smartprotocol.py
Labels: bug

#1028 Prepare 0.7.0.2
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: release-prep

#1030 Update changelog generator config
  .github_changelog_generator
  RELEASING.md
Labels: maintenance

#1031 Add L920(EU) v1.1.3 fixture
  SUPPORTED.md
  kasa/tests/fixtures/smart/L920-5(EU)_1.0_1.1.3.json
Labels: new device

#1020 Support child devices in all applicable cli commands
  kasa/cli.py
  kasa/device.py
  kasa/iot/iotstrip.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/tests/test_cli.py
Labels: enhancement

#1045 Prepare 0.7.0.3
  CHANGELOG.md
  pyproject.toml
Labels: release-prep

#1046 Add KS225(US) v1.1.0 fixture
  SUPPORTED.md
  kasa/tests/fixtures/smart/KS225(US)_1.0_1.1.0.json
Labels: maintenance

#1047 Add KS200M(US) v1.0.11 fixture
  SUPPORTED.md
  kasa/tests/fixtures/KS200M(US)_1.0_1.0.11.json
Labels: maintenance

#1037 Add KP400 v1.0.3 fixture
  SUPPORTED.md
  kasa/tests/fixtures/KP400(US)_3.0_1.0.3.json
Labels: maintenance

#1038 Structure cli into a package
  devtools/parse_pcap.py
  kasa/cli/__init__.py
  kasa/cli/__main__.py
  kasa/cli/main.py
  kasa/tests/test_cli.py
  pyproject.toml
Labels: maintenance

#1048 Fix light preset module when list contains lighting effects
  kasa/smart/modules/lightpreset.py
  kasa/tests/fixtures/smart/L920-5(EU)_1.0_1.1.3.json
Labels: bug

#1053 Bump project version to 0.7.0.3
  pyproject.toml
Labels: maintenance

#1054 Use first known thermostat state as main state
  kasa/smart/modules/temperaturecontrol.py
  kasa/tests/smart/modules/test_temperaturecontrol.py
Labels: bug

#1052 Defer module updates for less volatile modules
  kasa/aestransport.py
  kasa/exceptions.py
  kasa/httpclient.py
  kasa/smart/modules/cloud.py
  kasa/smart/modules/firmware.py
  kasa/smart/modules/led.py
  kasa/smart/modules/lighteffect.py
  kasa/smart/modules/lightpreset.py
  kasa/smart/modules/lightstripeffect.py
  kasa/smart/modules/lighttransition.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  kasa/smartprotocol.py
  kasa/tests/test_smartdevice.py
  kasa/tests/test_smartprotocol.py
Labels: bug

#1059 Prepare 0.7.0.4
  CHANGELOG.md
  pyproject.toml
Labels: release-prep

#1060 Bump version to 0.7.0.4
  pyproject.toml
Labels: release-prep

#1041 Decrypt KLAP data from PCAP files
  devtools/README.md
  devtools/parse_pcap_klap.py
  pyproject.toml
Labels: enhancement

#1064 Only refresh smart LightEffect module daily
  kasa/smart/modules/lighteffect.py
Labels: bug

#1077 0.7.0.5
  CHANGELOG.md
  kasa/discover.py
  kasa/iotprotocol.py
  kasa/klaptransport.py
  kasa/protocol.py
  kasa/smart/modules/lighteffect.py
  kasa/smart/smartdevice.py
  kasa/smartprotocol.py
  kasa/tests/discovery_fixtures.py
  kasa/tests/test_discovery.py
  kasa/tests/test_protocol.py
  kasa/tests/test_smartprotocol.py
  kasa/xortransport.py
  pyproject.toml
Labels: release-prep

#1078 Raise KasaException on decryption errors
  kasa/klaptransport.py
  kasa/tests/test_klapprotocol.py
Labels: bug

#1039 Split out main cli module into lazily loaded submodules
  kasa/cli/__main__.py
  kasa/cli/common.py
  kasa/cli/device.py
  kasa/cli/discover.py
  kasa/cli/feature.py
  kasa/cli/lazygroup.py
  kasa/cli/light.py
  kasa/cli/main.py
  kasa/cli/schedule.py
  kasa/cli/time.py
  kasa/cli/usage.py
  kasa/cli/wifi.py
  kasa/tests/test_cli.py
  pyproject.toml
Labels: maintenance

#1073 Expose reboot action
  docs/tutorial.py
  kasa/device.py
  kasa/feature.py
  kasa/iot/iotdevice.py
  kasa/smart/smartdevice.py
Labels: enhancement

#1079 Add support for T100 motion sensor
  README.md
  SUPPORTED.md
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/motionsensor.py
  kasa/tests/device_fixtures.py
  kasa/tests/fixtures/smart/child/T100(EU)_1.0_1.12.0.json
  kasa/tests/smart/modules/test_motionsensor.py
Labels: new device

#1082 Fix intermittently failing decryption error test
  kasa/tests/test_klapprotocol.py
Labels: maintenance

#1081 Fix mypy pre-commit hook on windows
  devtools/run-in-env.sh
  kasa/discover.py
Labels: maintenance

#1085 Fix generate_supported pre commit to run in venv
  .pre-commit-config.yaml
  devtools/run-in-env.sh
Labels: maintenance

#1087 Bump project version to 0.7.0.5
  pyproject.toml
Labels: maintenance

#1088 Merge patch into master
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  CHANGELOG.md
Labels: release-prep

#1080 Allow erroring modules to recover
  kasa/feature.py
  kasa/interfaces/energy.py
  kasa/iot/iotdevice.py
  kasa/iot/modules/ambientlight.py
  kasa/iot/modules/light.py
  kasa/smart/modules/alarm.py
  kasa/smart/modules/autooff.py
  kasa/smart/modules/batterysensor.py
  kasa/smart/modules/brightness.py
  kasa/smart/modules/cloud.py
  kasa/smart/modules/energy.py
  kasa/smart/modules/fan.py
  kasa/smart/modules/humiditysensor.py
  kasa/smart/modules/lighttransition.py
  kasa/smart/modules/reportmode.py
  kasa/smart/modules/temperaturecontrol.py
  kasa/smart/modules/temperaturesensor.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/test_feature.py
  kasa/tests/test_smartdevice.py
Labels: bug

#1076 Update RELEASING.md for patch releases
  RELEASING.md
Labels: maintenance

#1094 Prepare 0.7.1
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: release-prep
