Repository python-kasa/python-kasa, pull requests merged in 2024-06, with the labels that each got.

#936 Make device initialisation easier by reducing required imports
  devtools/dump_devinfo.py
  docs/source/guides.md
  docs/source/reference.md
  docs/tutorial.py
  kasa/__init__.py
  kasa/cli.py
  kasa/device.py
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/tests/test_device.py
  kasa/tests/test_device_factory.py
  kasa/tests/test_discovery.py
Labels: enhancement

#949 Do not raise on multi-request errors on child devices
  kasa/smartprotocol.py
  kasa/tests/test_smartprotocol.py
Labels: bug

#930 Fix P100 errors on multi-requests
  kasa/aestransport.py
  kasa/httpclient.py
  kasa/tests/test_aestransport.py
Labels: bug

#957 Fix fan speed level when off and derive smart fan module from common fan interface
  kasa/smart/modules/fan.py
  kasa/tests/smart/modules/test_fan.py
Labels: bug

#959 Ensure http delay logic works during default login attempt
  kasa/aestransport.py
Labels: bug

#961 Fix switching off light effects for iot lights strips
  kasa/iot/modules/lighteffect.py
  kasa/tests/fakeprotocol_iot.py
  kasa/tests/test_common_modules.py
Labels: bug

#956 Require update in cli for wifi commands
  kasa/cli.py
Labels: bug

#962 Prepare 0.7.0.dev3
  .github_changelog_generator
  CHANGELOG.md
  RELEASING.md
  poetry.lock
  pyproject.toml
Labels: release-prep

#967 Support smart child modules queries
  kasa/smart/modules/autooff.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/smart/modules/test_autooff.py
  kasa/tests/test_smartdevice.py
Labels: enhancement

#969 Prepare 0.7.0.dev4
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: release-prep

#971 Add supported check to light transition module
  kasa/smart/modules/lighttransition.py
Labels: bug

#972 Add fixture for L920-5(EU) 1.0.7
  SUPPORTED.md
  kasa/tests/fixtures/smart/L920-5(EU)_1.0_1.0.7.json
Labels: maintenance

#973 Handle unknown light effect names and only calculate effect list once
  kasa/smart/modules/lightstripeffect.py
Labels: enhancement

#974 Add type hints to feature set_value
  kasa/feature.py
Labels: enhancement

#978 Add timezone to on_since attributes
  kasa/iot/iotdevice.py
  kasa/iot/iotstrip.py
  kasa/smart/smartdevice.py
Labels: enhancement

#951 Add time sync command
  docs/source/cli.rst
  kasa/cli.py
  kasa/smart/modules/time.py
  kasa/tests/test_cli.py
Labels: enhancement

#982 Disallow non-targeted device commands
  kasa/cli.py
  kasa/tests/test_cli.py
Labels: bug

#976 Add common energy module and deprecate device emeter attributes
  kasa/device.py
  kasa/interfaces/__init__.py
  kasa/interfaces/energy.py
  kasa/iot/iotbulb.py
  kasa/iot/iotdevice.py
  kasa/iot/iotstrip.py
  kasa/iot/modules/emeter.py
  kasa/iot/modules/led.py
  kasa/module.py
  kasa/smart/modules/energy.py
  kasa/smart/smartdevice.py
  kasa/tests/test_device.py
  kasa/tests/test_emeter.py
  kasa/tests/test_iotdevice.py
Labels: enhancement

#984 Prepare 0.7.0.dev5
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: release-prep

#968 Update docs with more howto examples
  README.md
  docs/source/codeinfo.md
  docs/source/guides.md
  docs/source/guides/connect.md
  docs/source/guides/device.md
  docs/source/guides/discover.md
  docs/source/guides/energy.md
  docs/source/guides/feature.md
  docs/source/guides/light.md
  docs/source/guides/module.md
  docs/source/guides/strip.md
  docs/source/reference.md
  docs/source/tutorial.md
  docs/tutorial.py
  kasa/device.py
  kasa/feature.py
  kasa/interfaces/light.py
  kasa/interfaces/lighteffect.py
  kasa/interfaces/lightpreset.py
  kasa/module.py
  kasa/smart/modules/childdevice.py
  kasa/tests/test_readme_examples.py
Labels: documentation

#987 Fix to call update when only --device-family passed to cli
  kasa/cli.py
  kasa/tests/test_cli.py
Labels: bug

#990 Remove anyio dependency from pyproject.toml
  poetry.lock
  pyproject.toml
Labels: maintenance

#989 Configure mypy to run in virtual environment and fix resulting issues
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  devtools/bench/benchmark.py
  devtools/run-in-env.sh
  kasa/aestransport.py
  kasa/cli.py
  kasa/httpclient.py
  kasa/tests/discovery_fixtures.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/smart/modules/test_firmware.py
  kasa/tests/test_device.py
  kasa/tests/test_emeter.py
  kasa/tests/test_httpclient.py
  kasa/tests/test_iotdevice.py
  kasa/xortransport.py
  poetry.lock
  pyproject.toml
Labels: maintenance

#992 Drop python3.8 support
  .github/workflows/ci.yml
  kasa/aestransport.py
  kasa/device.py
  kasa/discover.py
  kasa/interfaces/lightpreset.py
  kasa/iot/iotdevice.py
  kasa/iot/modules/lightpreset.py
  kasa/smart/modules/firmware.py
  kasa/smart/modules/lightpreset.py
  kasa/smart/smartdevice.py
  kasa/tests/device_fixtures.py
  kasa/tests/test_iotdevice.py
  kasa/tests/test_smartdevice.py
  kasa/xortransport.py
  poetry.lock
  pyproject.toml
Labels: maintenance

#993 Add unit_getter for feature
  kasa/feature.py
  kasa/smart/modules/temperaturesensor.py
Labels: enhancement

#995 Update mode, time, rssi and report_interval feature names/units
  docs/tutorial.py
  kasa/feature.py
  kasa/iot/iotdevice.py
  kasa/iot/iotstrip.py
  kasa/smart/modules/reportmode.py
  kasa/smart/modules/temperaturecontrol.py
  kasa/smart/modules/time.py
  kasa/smart/smartdevice.py
Labels: enhancement

#997 Improve autooff name and unit
  kasa/smart/modules/autooff.py
Labels: enhancement

#994 Update README to be more approachable for new users
  README.md
Labels: documentation

#999 Cleanup README to use the new cli format
  README.md
Labels: documentation

#1000 Cleanup cli output
  kasa/cli.py
  kasa/tests/test_cli.py
Labels: enhancement

#1001 Demote device_time back to debug
  kasa/smart/modules/time.py
Labels: bug

#996 Add 0.7 api changes section to docs
  docs/source/deprecated.md
Labels: documentation

#998 Prepare 0.7.0
  .github_changelog_generator
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: release-prep

#1010 Fix iot strip so the children do not have led and cloud modules
  kasa/iot/iotstrip.py
Labels: bug

#1006 Require explicit feature type
  kasa/feature.py
  kasa/interfaces/energy.py
  kasa/iot/iotdevice.py
  kasa/iot/iotstrip.py
  kasa/smart/modules/alarm.py
  kasa/smart/modules/autooff.py
  kasa/smart/modules/firmware.py
  kasa/smart/modules/humiditysensor.py
  kasa/smart/modules/reportmode.py
  kasa/smart/modules/temperaturecontrol.py
  kasa/smart/modules/temperaturesensor.py
  kasa/smart/modules/time.py
  kasa/smart/modules/waterleaksensor.py
  kasa/smart/smartdevice.py
  kasa/tests/test_feature.py
Labels: bug

#1011 Fix post update hook for iot child devices
  kasa/iot/iotstrip.py
  kasa/tests/test_strip.py
Labels: bug

#1013 Disable lighttransition module on child devices
  kasa/smart/modules/lighttransition.py
Labels: bug

#1015 Prepare 0.7.0.1
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: release-prep

#1016 Handle unknown error codes gracefully
  kasa/aestransport.py
  kasa/exceptions.py
  kasa/smartprotocol.py
  kasa/tests/test_aestransport.py
  kasa/tests/test_smartprotocol.py
Labels: bug

#1017 Update light transition module to work with child devices
  kasa/feature.py
  kasa/smart/modules/lighttransition.py
  kasa/tests/device_fixtures.py
  kasa/tests/discovery_fixtures.py
  kasa/tests/fakeprotocol_smart.py
  kasa/tests/fixtureinfo.py
  kasa/tests/smart/modules/test_lighttransition.py
  kasa/tests/test_device_factory.py
Labels: bug

#1022 Cache SmartErrorCode creation
  kasa/aestransport.py
  kasa/exceptions.py
  kasa/smartprotocol.py
Labels: maintenance
