Repository python-kasa/python-kasa, pull requests merged in 2024-12, with the labels that each got.

#943 Add ssltransport for robovacs
  devtools/helpers/smartrequests.py
  kasa/cli/main.py
  kasa/device_factory.py
  kasa/device_type.py
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/smart/smartdevice.py
  kasa/transports/__init__.py
  kasa/transports/ssltransport.py
  tests/test_cli.py
  tests/test_device_factory.py
  tests/transports/test_ssltransport.py
Labels: enhancement, no-stale

#1328 Scrub more vacuum keys
  devtools/dump_devinfo.py
Labels: maintenance

#1333 Add link to related homeassistant-tapo-control
  README.md
Labels: documentation

#1319 Do not error when accessing smart device_type before update
  kasa/smart/smartdevice.py
  tests/discovery_fixtures.py
  tests/smart/test_smartdevice.py
Labels: bug

#1316 Provide alternative camera urls
  kasa/__init__.py
  kasa/smartcam/modules/camera.py
  tests/smartcam/modules/test_camera.py
  tests/smartcam/test_smartcamdevice.py
Labels: enhancement

#1343 Fix smartcam missing device id
  kasa/smartcam/smartcamdevice.py
  tests/test_device.py
Labels: bug

#1344 Fix update errors on hubs with unsupported children
  kasa/smart/smartdevice.py
  kasa/smartcam/smartcamdevice.py
Labels: bug

#1345 0.8.1
  CHANGELOG.md
  kasa/smart/smartdevice.py
  kasa/smartcam/smartcamdevice.py
  pyproject.toml
  tests/test_device.py
  uv.lock
Labels: release-prep

#1346 Merge patch into master
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1270 Add LinkieTransportV2 and basic IOT.IPCAMERA support
  kasa/cli/discover.py
  kasa/credentials.py
  kasa/device_factory.py
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/iot/__init__.py
  kasa/iot/iotcamera.py
  kasa/iot/iotdevice.py
  kasa/transports/__init__.py
  kasa/transports/linkietransport.py
  tests/fixtures/iotcam/EC60(US)_4.0_2.3.22.json
  tests/test_device.py
  tests/transports/test_linkietransport.py
Labels: enhancement

#1352 Add C520WS camera fixture
  README.md
  SUPPORTED.md
  tests/fixtures/smartcam/C520WS(US)_1.0_1.2.8.json
Labels: new device

#1355 Add KS200 (US) IOT Fixture and P115 (US) Smart Fixture
  README.md
  SUPPORTED.md
  tests/device_fixtures.py
  tests/fixtures/iot/KS200(US)_1.0_1.0.8.json
  tests/fixtures/smart/P115(US)_1.0_1.1.3.json
Labels: new device

#1361 Fix line endings in device_fixtures.py
  tests/device_fixtures.py
Labels: maintenance

#1347 Tweak RELEASING.md instructions for patch releases
  RELEASING.md
Labels: maintenance

#1342 Return raw discovery result in cli discover raw
  kasa/cli/discover.py
  kasa/discover.py
  kasa/json.py
  tests/test_cli.py
Labels: enhancement

#1335 Improve overheat reporting
  docs/tutorial.py
  kasa/feature.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/contactsensor.py
  kasa/smart/modules/overheatprotection.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  tests/smart/test_smartdevice.py
Labels: enhancement

#1363 Pass raw components to SmartChildDevice init
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smartcam/smartcamdevice.py
  tests/test_childdevice.py
  tests/test_device.py
Labels: maintenance

#1364 Update cli, light modules, and docs to use FeatureAttributes
  docs/tutorial.py
  kasa/cli/light.py
  kasa/interfaces/light.py
  kasa/interfaces/lighteffect.py
  kasa/iot/modules/light.py
  kasa/iot/modules/lightpreset.py
  kasa/smart/modules/light.py
  kasa/smart/modules/lightpreset.py
  tests/iot/test_iotbulb.py
  tests/smart/test_smartdevice.py
  tests/test_bulb.py
  tests/test_cli.py
  tests/test_common_modules.py
  tests/test_device.py
Labels: maintenance

#1367 Add homebridge-kasa-python link to README
  README.md
Labels: documentation

#1338 Use DeviceInfo consistently across devices
  kasa/cli/device.py
  kasa/device.py
  kasa/discover.py
  kasa/iot/iotdevice.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smartcam/smartcamdevice.py
  tests/device_fixtures.py
  tests/iot/test_iotdevice.py
  tests/smart/test_smartdevice.py
  tests/test_discovery.py
  tests/test_readme_examples.py
Labels: breaking change

#1365 Update docs for new FeatureAttribute behaviour
  docs/source/featureattributes.md
  docs/source/reference.md
  docs/source/topics.md
  kasa/module.py
Labels: documentation

#1370 Add bare bones homekit modules smart and smartcam devices
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/homekit.py
  kasa/smartcam/modules/__init__.py
  kasa/smartcam/modules/homekit.py
  tests/fakeprotocol_smart.py
  tests/smart/modules/test_homekit.py
Labels: enhancement

#1374 Force single for some smartcam requests
  kasa/protocols/smartprotocol.py
  tests/fakeprotocol_smartcam.py
  tests/protocols/test_smartprotocol.py
Labels: maintenance

#1380 Update docs for Tapo Lab Third-Party compatibility
  README.md
  SUPPORTED.md
Labels: documentation

#1382 Miscellaneous minor fixes to dump_devinfo
  devtools/dump_devinfo.py
Labels: maintenance

#1375 Enable saving of fixture files without git clone
  devtools/dump_devinfo.py
Labels: maintenance

#1377 Simplify get_protocol to prevent clashes with smartcam and robovac
  kasa/device_factory.py
  kasa/discover.py
  tests/test_device_factory.py
Labels: maintenance

#1384 Update C520WS fixture with new methods
  tests/fixtures/smartcam/C520WS(US)_1.0_1.2.8.json
Labels: maintenance

#1339 cli: print model, https, and lv for discover list
  kasa/cli/discover.py
  tests/discovery_fixtures.py
  tests/test_cli.py
Labels: enhancement

#1385 Add LensMask module to smartcam
  kasa/module.py
  kasa/smartcam/modules/__init__.py
  kasa/smartcam/modules/camera.py
  kasa/smartcam/modules/lensmask.py
  kasa/smartcam/smartcamdevice.py
  tests/smartcam/test_smartcamdevice.py
Labels: bug

#1379 Add C325WB(EU) 1.0 1.1.17 Fixture
  README.md
  SUPPORTED.md
  tests/fixtures/smartcam/C325WB(EU)_1.0_1.1.17.json
Labels: new device

#1390 Add TC70 3.0 1.3.11 fixture
  README.md
  SUPPORTED.md
  tests/fixtures/smartcam/TC70_3.0_1.3.11.json
Labels: new device

#1386 Fix lens mask required component and state
  kasa/smartcam/modules/camera.py
  kasa/smartcam/modules/lensmask.py
Labels: bug

#1389 Add smartcam detection modules
  kasa/smartcam/modules/__init__.py
  kasa/smartcam/modules/babycrydetection.py
  kasa/smartcam/modules/motiondetection.py
  kasa/smartcam/modules/persondetection.py
  kasa/smartcam/modules/tamperdetection.py
  kasa/smartcam/smartcammodule.py
  tests/smartcam/modules/test_babycrydetection.py
  tests/smartcam/modules/test_motiondetection.py
  tests/smartcam/modules/test_persondetection.py
  tests/smartcam/modules/test_tamperdetection.py
Labels: enhancement

#1392 Add rssi and signal_level to smartcam
  kasa/smartcam/modules/device.py
  kasa/smartcam/smartcamdevice.py
  kasa/smartcam/smartcammodule.py
Labels: enhancement

#1245 Fallback to other module data on get_energy_usage errors
  kasa/smart/modules/energy.py
  kasa/smart/smartmodule.py
  tests/smart/modules/test_energy.py
  tests/smart/test_smartdevice.py
Labels: bug

#1391 Handle KeyboardInterrupts in the cli better
  kasa/cli/common.py
  kasa/discover.py
Labels: maintenance

#1393 Handle smartcam device blocked response
  kasa/transports/sslaestransport.py
  tests/transports/test_sslaestransport.py
Labels: maintenance

#1395 Treat smartcam 500 errors after handshake as retryable
  kasa/httpclient.py
  kasa/transports/sslaestransport.py
  tests/transports/test_sslaestransport.py
Labels: bug

#1397 Add P135 1.0 1.2.0 fixture
  SUPPORTED.md
  tests/fixtures/smart/P135(US)_1.0_1.2.0.json
Labels: maintenance

#1398 Add C225(US) 2.0 1.0.11 fixture
  README.md
  SUPPORTED.md
  tests/fixtures/smartcam/C225(US)_2.0_1.0.11.json
Labels: new device

#1399 Add P210M(US) 1.0 1.0.3 fixture
  README.md
  SUPPORTED.md
  tests/device_fixtures.py
  tests/fixtures/smart/P210M(US)_1.0_1.0.3.json
  tests/test_cli.py
  tests/test_device.py
Labels: new device

#1396 Add P306(US) 1.0 1.1.2 fixture
  README.md
  SUPPORTED.md
  tests/device_fixtures.py
  tests/fixtures/smart/P306(US)_1.0_1.1.2.json
Labels: new device

#1401 Prepare 0.9.0
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1405 Add HS210(US) 3.0 1.0.10 IOT Fixture
  SUPPORTED.md
  tests/fixtures/iot/HS210(US)_3.0_1.0.10.json
Labels: maintenance
