Repository python-kasa/python-kasa, pull requests merged in 2025-01, with the labels that each got.

#1406 Add C210 2.0 1.3.11 fixture
  SUPPORTED.md
  devtools/generate_supported.py
  tests/fixtures/smartcam/C210_2.0_1.3.11.json
Labels: maintenance

#1412 Fix incorrect obd src echo
  kasa/cli/discover.py
Labels: bug

#1362 Update SslAesTransport for older firmware versions
  kasa/exceptions.py
  kasa/transports/sslaestransport.py
  tests/transports/test_sslaestransport.py
Labels: enhancement

#1417 Improve exception messages on credential mismatches
  kasa/transports/klaptransport.py
  kasa/transports/sslaestransport.py
Labels: documentation

#1419 Add S220 fixture
  README.md
  SUPPORTED.md
  tests/device_fixtures.py
  tests/fixtures/smart/child/S220(EU)_1.0_1.9.0.json
Labels: new device

#1418 Add S210 fixture
  README.md
  SUPPORTED.md
  tests/device_fixtures.py
  tests/fixtures/smart/child/S210(EU)_1.0_1.9.0.json
Labels: new device

#1414 Use repr() for enum values in Feature.__repr__
  kasa/feature.py
Labels: enhancement

#1424 Backoff after xor timeout and improve error reporting
  kasa/protocols/iotprotocol.py
  kasa/transports/xortransport.py
  tests/protocols/test_iotprotocol.py
Labels: bug

#1426 Prepare 0.9.1
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1427 Raise errors on single smartcam child requests
  kasa/protocols/smartcamprotocol.py
Labels: maintenance

#1433 Add fixture for C720 camera
  README.md
  SUPPORTED.md
  tests/fixtures/smartcam/C720(US)_1.0_1.2.3.json
Labels: new device

#1428 Add tests for dump_devinfo parent/child smartcam fixture generation
  tests/fakeprotocol_smart.py
  tests/fakeprotocol_smartcam.py
  tests/fixtureinfo.py
  tests/test_devtools.py
Labels: maintenance

#1439 Add more redactors for smartcams
  kasa/protocols/smartprotocol.py
Labels: maintenance

#1443 ssltransport: use debug logger for sending requests
  kasa/transports/ssltransport.py
Labels: bug

#1446 Add required sphinx.configuration
  .readthedocs.yml
Labels: maintenance

#1438 Update hub children on first update and delay subsequent updates
  kasa/smart/modules/devicemodule.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smart/smartmodule.py
  kasa/smartcam/modules/device.py
  tests/smart/test_smartdevice.py
Labels: enhancement

#1413 Add smartcam child device support for smartcam hubs
  devtools/dump_devinfo.py
  devtools/generate_supported.py
  kasa/smartcam/__init__.py
  kasa/smartcam/smartcamchild.py
  kasa/smartcam/smartcamdevice.py
  tests/device_fixtures.py
  tests/fakeprotocol_smart.py
  tests/fakeprotocol_smartcam.py
  tests/fixtureinfo.py
  tests/smartcam/modules/test_camera.py
  tests/smartcam/test_smartcamdevice.py
  tests/test_device.py
  tests/test_devtools.py
Labels: enhancement

#1448 Add D230(EU) 1.20 1.1.19 fixture
  README.md
  SUPPORTED.md
  tests/fixtures/smartcam/H200(EU)_1.0_1.3.6.json
  tests/fixtures/smartcam/child/D230(EU)_1.20_1.1.19.json
Labels: new device

#1449 Make uses_http a readonly property of device config
  kasa/device_factory.py
  kasa/deviceconfig.py
  kasa/discover.py
  tests/fixtures/serialization/deviceconfig_camera-aes-https.json
  tests/fixtures/serialization/deviceconfig_plug-klap.json
  tests/fixtures/serialization/deviceconfig_plug-xor.json
  tests/test_discovery.py
Labels: breaking change

#944 Initial support for vacuums (clean module)
  README.md
  SUPPORTED.md
  devtools/generate_supported.py
  devtools/helpers/smartrequests.py
  kasa/device_factory.py
  kasa/discover.py
  kasa/exceptions.py
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/clean.py
  tests/device_fixtures.py
  tests/fakeprotocol_smart.py
  tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json
  tests/smart/modules/test_clean.py
  tests/test_device_factory.py
  tests/test_discovery.py
Labels: enhancement, no-stale

#1437 Fix discover cli command with host
  kasa/cli/common.py
  kasa/cli/device.py
  kasa/cli/discover.py
  kasa/cli/main.py
Labels: bug

#1450 Allow update of camera modules after setting values
  kasa/smartcam/modules/alarm.py
  kasa/smartcam/modules/babycrydetection.py
  kasa/smartcam/modules/camera.py
  kasa/smartcam/modules/led.py
  kasa/smartcam/modules/lensmask.py
  kasa/smartcam/modules/motiondetection.py
  kasa/smartcam/modules/persondetection.py
  kasa/smartcam/modules/tamperdetection.py
  kasa/smartcam/modules/time.py
Labels: enhancement

#1332 Add vacuum speaker controls
  devtools/helpers/smartrequests.py
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/speaker.py
  tests/fakeprotocol_smart.py
  tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json
  tests/smart/modules/test_speaker.py
Labels: enhancement

#1452 Add battery module to smartcam devices
  kasa/smartcam/modules/__init__.py
  kasa/smartcam/modules/battery.py
  kasa/smartcam/smartcamchild.py
  kasa/smartcam/smartcamdevice.py
  kasa/smartcam/smartcammodule.py
  tests/device_fixtures.py
  tests/fakeprotocol_smart.py
  tests/fakeprotocol_smartcam.py
  tests/smart/test_smartdevice.py
  tests/smartcam/modules/test_battery.py
Labels: enhancement

#1420 Fallback to is_low for batterysensor's battery_low
  kasa/smart/modules/batterysensor.py
Labels: bug

#1455 Add commit-hook to prettify JSON files
  .pre-commit-config.yaml
  tests/fixtures/serialization/deviceconfig_camera-aes-https.json
  tests/fixtures/serialization/deviceconfig_plug-klap.json
  tests/fixtures/serialization/deviceconfig_plug-xor.json
  tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json
  tests/fixtures/smart/child/T310(EU)_1.0_1.5.0.json
  tests/fixtures/smart/child/T315(EU)_1.0_1.7.0.json
Labels: maintenance

#1457 Add setting to change clean count
  kasa/smart/modules/clean.py
  tests/smart/modules/test_clean.py
Labels: enhancement

#1456 Add mop module
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/mop.py
  tests/smart/modules/test_mop.py
Labels: enhancement

#1454 Enable dynamic hub child creation and deletion on update
  kasa/smart/modules/childdevice.py
  kasa/smart/smartchilddevice.py
  kasa/smart/smartdevice.py
  kasa/smartcam/modules/childdevice.py
  kasa/smartcam/smartcamdevice.py
  tests/fakeprotocol_smart.py
  tests/fakeprotocol_smartcam.py
  tests/smart/test_smartdevice.py
Labels: enhancement

#1458 Add setting to change carpet clean mode
  devtools/helpers/smartrequests.py
  kasa/smart/modules/clean.py
  tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json
  tests/smart/modules/test_clean.py
Labels: enhancement

#1461 Add childlock module for vacuums
  devtools/helpers/smartrequests.py
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/childlock.py
  tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json
  tests/smart/modules/test_childlock.py
Labels: enhancement

#1465 Add smartcam pet detection toggle module
  kasa/smartcam/modules/__init__.py
  kasa/smartcam/modules/petdetection.py
  kasa/smartcam/smartcammodule.py
  tests/smartcam/modules/test_petdetection.py
Labels: enhancement

#1466 Add C220(EU) 1.0 1.2.2 camera fixture
  README.md
  SUPPORTED.md
  tests/fixtures/smartcam/C220(EU)_1.0_1.2.2.json
Labels: new device

#859 Add support for pairing devices with hubs
  kasa/cli/hub.py
  kasa/cli/main.py
  kasa/feature.py
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/childsetup.py
  kasa/smart/smartdevice.py
  tests/cli/__init__.py
  tests/cli/test_hub.py
  tests/conftest.py
  tests/fakeprotocol_smart.py
  tests/fixtures/smart/H100(EU)_1.0_1.5.10.json
  tests/smart/modules/test_childsetup.py
  tests/smart/test_smartdevice.py
  tests/test_cli.py
  tests/test_feature.py
Labels: enhancement, no-stale

#945 Add support for cleaning records
  docs/tutorial.py
  kasa/cli/main.py
  kasa/cli/vacuum.py
  kasa/feature.py
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/cleanrecords.py
  kasa/smart/smartdevice.py
  tests/cli/test_vacuum.py
  tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json
  tests/smart/modules/test_cleanrecords.py
  tests/smart/test_smartdevice.py
Labels: enhancement, no-stale

#1327 Add consumables module for vacuums
  kasa/cli/vacuum.py
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/consumables.py
  tests/cli/test_vacuum.py
  tests/fakeprotocol_smart.py
  tests/smart/modules/test_consumables.py
Labels: enhancement

#1297 Deprecate legacy light module is_capability checks
  kasa/device.py
  kasa/interfaces/light.py
  kasa/iot/modules/light.py
  kasa/smart/modules/light.py
  tests/test_bulb.py
Labels: breaking change

#1415 Allow https for klaptransport
  README.md
  SUPPORTED.md
  devtools/dump_devinfo.py
  kasa/cli/discover.py
  kasa/device_factory.py
  kasa/deviceconfig.py
  kasa/discover.py
  kasa/protocols/smartprotocol.py
  kasa/transports/aestransport.py
  kasa/transports/klaptransport.py
  kasa/transports/linkietransport.py
  kasa/transports/sslaestransport.py
  kasa/transports/ssltransport.py
  tests/discovery_fixtures.py
  tests/fixtures/smart/RV30 Max(US)_1.0_1.2.0.json
  tests/smart/modules/test_clean.py
  tests/test_cli.py
  tests/test_device_factory.py
  tests/test_discovery.py
Labels: enhancement

#1471 Enable CI workflow on PRs to feat/ fix/ and janitor/
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: maintenance

#1475 Add D100C(US) 1.0 1.1.3 fixture
  README.md
  SUPPORTED.md
  tests/fixtures/smart/D100C(US)_1.0_1.1.3.json
Labels: new device

#1476 Add D130(US) 1.0 1.1.9 fixture
  README.md
  SUPPORTED.md
  tests/fixtures/smartcam/D130(US)_1.0_1.1.9.json
Labels: new device

#1469 Add childsetup module to smartcam hubs
  kasa/smart/modules/childsetup.py
  kasa/smart/smartdevice.py
  kasa/smartcam/modules/__init__.py
  kasa/smartcam/modules/childsetup.py
  kasa/smartcam/smartcamdevice.py
  kasa/smartcam/smartcammodule.py
  tests/fakeprotocol_smartcam.py
  tests/smartcam/modules/test_childsetup.py
  tests/test_cli.py
  tests/test_feature.py
Labels: enhancement

#1477 Update test framework to support smartcam device discovery.
  kasa/discover.py
  tests/discovery_fixtures.py
  tests/test_device_factory.py
Labels: maintenance

#639 Fix iot strip turn on and off from parent
  kasa/iot/iotstrip.py
  tests/fakeprotocol_iot.py
  tests/iot/test_iotdevice.py
  tests/test_feature.py
Labels: bug

#1470 Add common childsetup interface
  docs/source/guides/strip.md
  docs/tutorial.py
  kasa/cli/hub.py
  kasa/discover.py
  kasa/interfaces/__init__.py
  kasa/interfaces/childsetup.py
  kasa/module.py
  kasa/smart/modules/childsetup.py
  kasa/smartcam/modules/childsetup.py
  tests/cli/test_hub.py
  tests/device_fixtures.py
  tests/fakeprotocol_smart.py
  tests/smart/modules/test_childsetup.py
  tests/smartcam/modules/test_childsetup.py
  tests/test_readme_examples.py
Labels: enhancement

#1482 Update ruff to 0.9
  .pre-commit-config.yaml
  devtools/parse_pcap_klap.py
  kasa/cli/hub.py
  kasa/cli/lazygroup.py
  kasa/iot/iotdimmer.py
  kasa/iot/modules/lightpreset.py
  kasa/protocols/iotprotocol.py
  kasa/protocols/smartprotocol.py
  kasa/transports/xortransport.py
  pyproject.toml
  tests/fakeprotocol_smartcam.py
  tests/smart/test_smartdevice.py
  tests/test_cli.py
  tests/transports/test_aestransport.py
  tests/transports/test_sslaestransport.py
  uv.lock
Labels: maintenance

#1481 Cancel in progress CI workflows after new pushes
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: maintenance

#1483 Report 0 for instead of None for zero current and voltage
  kasa/smart/modules/energy.py
Labels: bug

#1263 Add ADC Value to PIR Enabled Switches
  kasa/cli/feature.py
  kasa/feature.py
  kasa/iot/modules/motion.py
  tests/fakeprotocol_iot.py
  tests/iot/modules/test_motion.py
  tests/test_cli.py
  tests/test_feature.py
Labels: enhancement

#1480 Disable iot camera creation until more complete
  kasa/device_factory.py
Labels: bug

#1337 Add powerprotection module
  kasa/module.py
  kasa/smart/modules/__init__.py
  kasa/smart/modules/powerprotection.py
  tests/fakeprotocol_smart.py
  tests/smart/modules/test_powerprotection.py
Labels: enhancement

#1340 Allow passing alarm parameter overrides
  kasa/smart/modules/alarm.py
  tests/fakeprotocol_smart.py
  tests/smart/modules/test_alarm.py
Labels: enhancement, breaking change

#1479 Add common alarm interface
  kasa/interfaces/__init__.py
  kasa/interfaces/alarm.py
  kasa/module.py
  kasa/smart/modules/alarm.py
  kasa/smartcam/modules/alarm.py
  tests/fakeprotocol_smartcam.py
  tests/smartcam/modules/test_alarm.py
Labels: enhancement

#1485 Change category for empty dustbin feature from Primary to Config
  kasa/smart/modules/dustbin.py
Labels: bug

#1486 Convert carpet_clean_mode to carpet_boost switch
  kasa/smart/modules/clean.py
  tests/smart/modules/test_clean.py
Labels: bug

#1473 Prepare 0.10.0
  .pre-commit-config.yaml
  CHANGELOG.md
  RELEASING.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1491 Do not return empty string for custom light effect name
  kasa/interfaces/lighteffect.py
  kasa/iot/modules/lighteffect.py
  kasa/smart/modules/lightstripeffect.py
Labels: bug

#1478 Add module.device to the public api
  kasa/module.py
  tests/iot/test_iotdevice.py
  tests/smart/modules/test_fan.py
  tests/smart/test_smartdevice.py
  tests/test_common_modules.py
Labels: maintenance

#1489 Add FeatureAttributes to smartcam Alarm
  kasa/interfaces/energy.py
  kasa/smart/smartmodule.py
  kasa/smartcam/modules/alarm.py
  tests/test_common_modules.py
Labels: bug
