Repository python-kasa/python-kasa, pull requests merged in 2025-02, with the labels that each got.

#1488 dustbin_mode: add 'off' mode for cleaner downstream impl
  kasa/smart/modules/dustbin.py
  tests/smart/modules/test_dustbin.py
Labels: enhancement

#1484 Add Dimmer Configuration Support
  kasa/iot/iotdimmer.py
  kasa/iot/modules/__init__.py
  kasa/iot/modules/dimmer.py
  kasa/module.py
  tests/iot/modules/test_dimmer.py
Labels: enhancement

#1494 Prepare 0.10.1
  .pre-commit-config.yaml
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: release-prep

#1497 Add L530E(TW) 2.0 1.1.1 fixture
  SUPPORTED.md
  tests/fixtures/smart/L530E(TW)_2.0_1.1.1.json
Labels: maintenance

#1500 Do not crash on missing build number in fw version
  devtools/dump_devinfo.py
  devtools/helpers/smartrequests.py
  kasa/cli/device.py
  kasa/device.py
  kasa/iot/iotdevice.py
  kasa/smart/smartdevice.py
  kasa/smartcam/smartcamchild.py
  kasa/smartcam/smartcamdevice.py
  tests/fixtures/smart/child/T310(US)_1.0_1.5.0.json
Labels: bug

#1502 Add L530B(EU) 3.0 1.1.9 fixture
  README.md
  SUPPORTED.md
  tests/fixtures/smart/L530B(EU)_3.0_1.1.9.json
Labels: new device

#1501 Add fixtures for new versions of H100, P110, and T100 devices
  SUPPORTED.md
  tests/fixtures/smart/H100(AU)_1.0_1.5.23.json
  tests/fixtures/smart/P110(AU)_1.0_1.3.1.json
  tests/fixtures/smart/child/T100(US)_1.0_1.12.0.json
Labels: maintenance

#1512 Add a note to emeter guide being kasa-only
  docs/source/guides/energy.md
Labels: documentation
